In [1]:
from imutils.video import VideoStream
import argparse
import imutils
import time
import cv2
import sys
import numpy as np
import os

In [32]:
import cv2
import numpy as np

all_camera_idx_available = []

for camera_idx in range(-100, 900):
    cap = cv2.VideoCapture(camera_idx)
    if cap.isOpened():
        print(f'Camera index available: {camera_idx}')
        all_camera_idx_available.append(camera_idx)
        cap.release()

Camera index available: 0


In [25]:
vs.stop()

In [2]:
arucoDict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_4X4_50)
arucoParams = cv2.aruco.DetectorParameters_create()
print("[INFO] starting video stream...")
vs = VideoStream(src=0).start()
time.sleep(2.0)

[INFO] starting video stream...


In [4]:
while True:
    frame = vs.read()

    image = imutils.resize(frame, width = 1000)
    (corners, ids, rejected) = cv2.aruco.detectMarkers(image, arucoDict, parameters=arucoParams)
    if len(corners) > 0:
        # flatten the ArUco IDs list
        ids = ids.flatten()
        # loop over the detected ArUCo corners
        for (markerCorner, markerID) in zip(corners, ids):
            # extract the marker corners (which are always returned in
            # top-left, top-right, bottom-right, and bottom-left order)
            #print(markerCorner)
            print(markerCorner)
            #corners = markerCorner.reshape((4, 1))
            (topLeft, topRight, bottomRight, bottomLeft) = markerCorner[0]
            # convert each of the (x, y)-coordinate pairs to integers
            topRight = (int(topRight[0]), int(topRight[1]))
            bottomRight = (int(bottomRight[0]), int(bottomRight[1]))
            bottomLeft = (int(bottomLeft[0]), int(bottomLeft[1]))
            topLeft = (int(topLeft[0]), int(topLeft[1]))

            # draw the bounding box of the ArUCo detection
            cv2.line(image, topLeft, topRight, (0, 255, 0), 2)
            cv2.line(image, topRight, bottomRight, (0, 255, 0), 2)
            cv2.line(image, bottomRight, bottomLeft, (0, 255, 0), 2)
            cv2.line(image, bottomLeft, topLeft, (0, 255, 0), 2)
            # compute and draw the center (x, y)-coordinates of the ArUco
            # marker
            cX = int((topLeft[0] + bottomRight[0]) / 2.0)
            cY = int((topLeft[1] + bottomRight[1]) / 2.0)
            cv2.circle(image, (cX, cY), 4, (0, 0, 255), -1)
            # draw the ArUco marker ID on the image
            cv2.putText(image, str(markerID),
                (topLeft[0], topLeft[1] - 15), cv2.FONT_HERSHEY_SIMPLEX,
                0.5, (0, 255, 0), 2)
            print("[INFO] ArUco marker ID: {}".format(markerID))
    # show the output image
    cv2.imshow("Image", image)
    key = cv2.waitKey(1) & 0xFF
    
    if key == ord("q"):
        break
cv2.destroyAllWindows()
vs.stop()

[[[154. 363.]
  [277. 370.]
  [291. 469.]
  [154. 478.]]]
[INFO] ArUco marker ID: 1
[[[154. 363.]
  [277. 370.]
  [291. 469.]
  [154. 478.]]]
[INFO] ArUco marker ID: 1
[[[154. 363.]
  [277. 370.]
  [291. 469.]
  [154. 478.]]]
[INFO] ArUco marker ID: 1
[[[322. 339.]
  [439. 354.]
  [424. 473.]
  [301. 460.]]]
[INFO] ArUco marker ID: 2
[[[322. 339.]
  [439. 354.]
  [424. 473.]
  [301. 460.]]]
[INFO] ArUco marker ID: 2
[[[322. 339.]
  [439. 354.]
  [424. 473.]
  [301. 460.]]]
[INFO] ArUco marker ID: 2
[[[311. 345.]
  [435. 354.]
  [423. 479.]
  [298. 470.]]]
[INFO] ArUco marker ID: 2
[[[ 35. 311.]
  [147. 329.]
  [146. 446.]
  [ 32. 426.]]]
[INFO] ArUco marker ID: 0
[[[ 32. 447.]
  [146. 465.]
  [164. 550.]
  [ 56. 528.]]]
[INFO] ArUco marker ID: 3
[[[ 32. 447.]
  [146. 465.]
  [164. 550.]
  [ 56. 528.]]]
[INFO] ArUco marker ID: 3
[[[ 32. 447.]
  [146. 465.]
  [164. 550.]
  [ 56. 528.]]]
[INFO] ArUco marker ID: 3
[[[ 61. 435.]
  [178. 458.]
  [178. 556.]
  [ 65. 531.]]]
[INFO] ArUco marke

[[[140. 360.]
  [251. 373.]
  [258. 479.]
  [147. 469.]]]
[INFO] ArUco marker ID: 6
[[[264. 237.]
  [386. 246.]
  [381. 373.]
  [262. 360.]]]
[INFO] ArUco marker ID: 4
[[[138. 227.]
  [251. 237.]
  [250. 359.]
  [139. 347.]]]
[INFO] ArUco marker ID: 3
[[[415. 110.]
  [542. 125.]
  [532. 245.]
  [401. 233.]]]
[INFO] ArUco marker ID: 2
[[[275.  98.]
  [402. 109.]
  [387. 233.]
  [265. 224.]]]
[INFO] ArUco marker ID: 1
[[[143.  91.]
  [262.  97.]
  [252. 223.]
  [138. 214.]]]
[INFO] ArUco marker ID: 0
[[[262. 373.]
  [381. 384.]
  [385. 493.]
  [272. 480.]]]
[INFO] ArUco marker ID: 7
[[[139. 360.]
  [250. 371.]
  [259. 479.]
  [149. 469.]]]
[INFO] ArUco marker ID: 6
[[[264. 236.]
  [386. 245.]
  [380. 372.]
  [262. 359.]]]
[INFO] ArUco marker ID: 4
[[[138. 227.]
  [251. 235.]
  [250. 358.]
  [139. 347.]]]
[INFO] ArUco marker ID: 3
[[[276.  98.]
  [402. 108.]
  [387. 231.]
  [265. 223.]]]
[INFO] ArUco marker ID: 1
[[[144.  91.]
  [263.  97.]
  [251. 222.]
  [138. 214.]]]
[INFO] ArUco marke

[[[162. 373.]
  [252. 387.]
  [253. 503.]
  [154. 487.]]]
[INFO] ArUco marker ID: 6
[[[265. 251.]
  [388. 257.]
  [386. 381.]
  [264. 375.]]]
[INFO] ArUco marker ID: 4
[[[160. 245.]
  [253. 251.]
  [252. 374.]
  [162. 360.]]]
[INFO] ArUco marker ID: 3
[[[157. 240.]
  [262. 247.]
  [258. 375.]
  [148. 363.]]]
[INFO] ArUco marker ID: 3
[[[172. 104.]
  [267. 103.]
  [265. 234.]
  [158. 224.]]]
[INFO] ArUco marker ID: 0
[[[274. 396.]
  [399. 405.]
  [400. 513.]
  [277. 512.]]]
[INFO] ArUco marker ID: 7
[[[150. 246.]
  [266. 255.]
  [260. 384.]
  [145. 371.]]]
[INFO] ArUco marker ID: 3
[[[151. 391.]
  [266. 406.]
  [266. 521.]
  [149. 512.]]]
[INFO] ArUco marker ID: 6
[[[280. 263.]
  [408. 269.]
  [403. 399.]
  [280. 391.]]]
[INFO] ArUco marker ID: 4
[[[152. 254.]
  [267. 263.]
  [265. 390.]
  [151. 376.]]]
[INFO] ArUco marker ID: 3
[[[282. 408.]
  [406. 414.]
  [409. 518.]
  [286. 522.]]]
[INFO] ArUco marker ID: 7
[[[157. 398.]
  [269. 409.]
  [272. 522.]
  [157. 518.]]]
[INFO] ArUco marke

[[[378. 402.]
  [505. 401.]
  [506. 530.]
  [378. 531.]]]
[INFO] ArUco marker ID: 8
[[[102. 403.]
  [225. 403.]
  [223. 530.]
  [ 98. 529.]]]
[INFO] ArUco marker ID: 6
[[[239. 402.]
  [364. 402.]
  [362. 531.]
  [237. 530.]]]
[INFO] ArUco marker ID: 7
[[[247. 266.]
  [369. 267.]
  [364. 388.]
  [238. 388.]]]
[INFO] ArUco marker ID: 4
[[[113. 267.]
  [234. 267.]
  [225. 389.]
  [103. 389.]]]
[INFO] ArUco marker ID: 3
[[[383. 265.]
  [505. 267.]
  [504. 388.]
  [378. 387.]]]
[INFO] ArUco marker ID: 5
[[[136. 152.]
  [253. 157.]
  [235. 254.]
  [115. 255.]]]
[INFO] ArUco marker ID: 0
[[[238. 397.]
  [362. 396.]
  [363. 526.]
  [238. 526.]]]
[INFO] ArUco marker ID: 7
[[[100. 401.]
  [223. 398.]
  [224. 526.]
  [ 98. 525.]]]
[INFO] ArUco marker ID: 6
[[[377. 397.]
  [505. 396.]
  [506. 525.]
  [378. 527.]]]
[INFO] ArUco marker ID: 8
[[[114. 263.]
  [233. 263.]
  [224. 385.]
  [102. 386.]]]
[INFO] ArUco marker ID: 3
[[[247. 262.]
  [368. 263.]
  [363. 384.]
  [238. 384.]]]
[INFO] ArUco marke

[[[ 89. 381.]
  [212. 378.]
  [214. 505.]
  [ 87. 508.]]]
[INFO] ArUco marker ID: 6
[[[226. 378.]
  [352. 375.]
  [354. 504.]
  [227. 505.]]]
[INFO] ArUco marker ID: 7
[[[366. 375.]
  [494. 372.]
  [496. 501.]
  [368. 504.]]]
[INFO] ArUco marker ID: 8
[[[ 95. 243.]
  [215. 239.]
  [213. 364.]
  [ 90. 367.]]]
[INFO] ArUco marker ID: 3
[[[229. 239.]
  [352. 235.]
  [352. 361.]
  [226. 364.]]]
[INFO] ArUco marker ID: 4
[[[366. 235.]
  [490. 231.]
  [493. 358.]
  [366. 361.]]]
[INFO] ArUco marker ID: 5
[[[109. 118.]
  [228. 117.]
  [216. 227.]
  [ 96. 230.]]]
[INFO] ArUco marker ID: 0
[[[240. 117.]
  [359. 115.]
  [352. 223.]
  [230. 226.]]]
[INFO] ArUco marker ID: 1
[[[372. 114.]
  [489. 109.]
  [490. 218.]
  [366. 222.]]]
[INFO] ArUco marker ID: 2
[[[ 89. 382.]
  [212. 379.]
  [214. 506.]
  [ 88. 509.]]]
[INFO] ArUco marker ID: 6
[[[226. 379.]
  [352. 376.]
  [354. 504.]
  [227. 506.]]]
[INFO] ArUco marker ID: 7
[[[366. 376.]
  [494. 373.]
  [496. 502.]
  [367. 505.]]]
[INFO] ArUco marke

[INFO] ArUco marker ID: 4
[[[367. 242.]
  [491. 238.]
  [493. 365.]
  [364. 367.]]]
[INFO] ArUco marker ID: 5
[[[119. 130.]
  [234. 130.]
  [218. 233.]
  [ 98. 236.]]]
[INFO] ArUco marker ID: 0
[[[223. 384.]
  [349. 381.]
  [351. 512.]
  [222. 514.]]]
[INFO] ArUco marker ID: 7
[[[ 86. 386.]
  [210. 384.]
  [208. 514.]
  [ 78. 516.]]]
[INFO] ArUco marker ID: 6
[[[365. 381.]
  [493. 379.]
  [495. 510.]
  [365. 513.]]]
[INFO] ArUco marker ID: 8
[[[ 96. 249.]
  [217. 245.]
  [210. 370.]
  [ 86. 371.]]]
[INFO] ArUco marker ID: 3
[[[230. 245.]
  [353. 242.]
  [351. 367.]
  [223. 369.]]]
[INFO] ArUco marker ID: 4
[[[367. 241.]
  [491. 238.]
  [493. 365.]
  [365. 367.]]]
[INFO] ArUco marker ID: 5
[[[117. 130.]
  [233. 129.]
  [217. 233.]
  [ 97. 235.]]]
[INFO] ArUco marker ID: 0
[[[247. 128.]
  [362. 127.]
  [353. 230.]
  [231. 232.]]]
[INFO] ArUco marker ID: 1
[[[375. 126.]
  [491. 120.]
  [490. 226.]
  [367. 229.]]]
[INFO] ArUco marker ID: 2
[[[223. 384.]
  [351. 382.]
  [351. 512.]
  [222. 

[INFO] ArUco marker ID: 0
[[[241. 122.]
  [359. 119.]
  [352. 231.]
  [229. 233.]]]
[INFO] ArUco marker ID: 1
[[[372. 118.]
  [491. 112.]
  [490. 227.]
  [366. 230.]]]
[INFO] ArUco marker ID: 2
[[[ 90. 388.]
  [212. 387.]
  [214. 513.]
  [ 88. 515.]]]
[INFO] ArUco marker ID: 6
[[[226. 387.]
  [352. 385.]
  [354. 512.]
  [228. 513.]]]
[INFO] ArUco marker ID: 7
[[[366. 384.]
  [494. 382.]
  [496. 509.]
  [368. 512.]]]
[INFO] ArUco marker ID: 8
[[[229. 247.]
  [352. 244.]
  [352. 370.]
  [227. 373.]]]
[INFO] ArUco marker ID: 4
[[[ 96. 251.]
  [215. 247.]
  [213. 372.]
  [ 90. 374.]]]
[INFO] ArUco marker ID: 3
[[[365. 244.]
  [492. 240.]
  [494. 368.]
  [366. 370.]]]
[INFO] ArUco marker ID: 5
[[[110. 125.]
  [228. 123.]
  [217. 234.]
  [ 97. 237.]]]
[INFO] ArUco marker ID: 0
[[[241. 122.]
  [359. 120.]
  [352. 231.]
  [229. 234.]]]
[INFO] ArUco marker ID: 1
[[[373. 118.]
  [491. 112.]
  [491. 227.]
  [366. 230.]]]
[INFO] ArUco marker ID: 2
[[[ 90. 388.]
  [212. 387.]
  [215. 513.]
  [ 89. 

[[[ 94. 389.]
  [214. 388.]
  [219. 512.]
  [ 96. 513.]]]
[INFO] ArUco marker ID: 6
[[[228. 388.]
  [353. 387.]
  [357. 511.]
  [233. 512.]]]
[INFO] ArUco marker ID: 7
[[[367. 387.]
  [494. 384.]
  [497. 509.]
  [370. 512.]]]
[INFO] ArUco marker ID: 8
[[[ 95. 252.]
  [214. 248.]
  [214. 374.]
  [ 94. 375.]]]
[INFO] ArUco marker ID: 3
[[[227. 248.]
  [351. 246.]
  [353. 372.]
  [228. 374.]]]
[INFO] ArUco marker ID: 4
[[[364. 245.]
  [492. 242.]
  [494. 371.]
  [367. 373.]]]
[INFO] ArUco marker ID: 5
[[[103. 119.]
  [220. 116.]
  [214. 235.]
  [ 95. 238.]]]
[INFO] ArUco marker ID: 0
[[[233. 116.]
  [353. 111.]
  [351. 232.]
  [228. 235.]]]
[INFO] ArUco marker ID: 1
[[[365. 110.]
  [490. 103.]
  [492. 227.]
  [365. 232.]]]
[INFO] ArUco marker ID: 2
[[[367. 386.]
  [494. 385.]
  [497. 509.]
  [370. 513.]]]
[INFO] ArUco marker ID: 8
[[[ 94. 389.]
  [214. 388.]
  [219. 512.]
  [ 96. 513.]]]
[INFO] ArUco marker ID: 6
[[[228. 388.]
  [352. 386.]
  [356. 512.]
  [233. 512.]]]
[INFO] ArUco marke

[[[ 94. 392.]
  [214. 390.]
  [219. 514.]
  [ 95. 516.]]]
[INFO] ArUco marker ID: 6
[[[228. 390.]
  [353. 388.]
  [356. 515.]
  [232. 515.]]]
[INFO] ArUco marker ID: 7
[[[367. 388.]
  [495. 386.]
  [498. 512.]
  [371. 516.]]]
[INFO] ArUco marker ID: 8
[[[ 96. 254.]
  [215. 251.]
  [215. 376.]
  [ 94. 377.]]]
[INFO] ArUco marker ID: 3
[[[227. 251.]
  [351. 247.]
  [353. 374.]
  [228. 376.]]]
[INFO] ArUco marker ID: 4
[[[365. 247.]
  [492. 243.]
  [495. 372.]
  [367. 375.]]]
[INFO] ArUco marker ID: 5
[[[235. 118.]
  [355. 114.]
  [351. 234.]
  [228. 237.]]]
[INFO] ArUco marker ID: 1
[[[103. 122.]
  [221. 118.]
  [215. 237.]
  [ 96. 240.]]]
[INFO] ArUco marker ID: 0
[[[367. 114.]
  [490. 106.]
  [492. 230.]
  [366. 234.]]]
[INFO] ArUco marker ID: 2
[[[ 94. 391.]
  [215. 390.]
  [219. 514.]
  [ 96. 515.]]]
[INFO] ArUco marker ID: 6
[[[228. 390.]
  [353. 388.]
  [357. 515.]
  [232. 514.]]]
[INFO] ArUco marker ID: 7
[[[ 96. 254.]
  [214. 250.]
  [215. 376.]
  [ 95. 378.]]]
[INFO] ArUco marke

[[[230. 392.]
  [355. 390.]
  [359. 517.]
  [234. 516.]]]
[INFO] ArUco marker ID: 7
[[[ 97. 393.]
  [217. 392.]
  [221. 517.]
  [ 98. 518.]]]
[INFO] ArUco marker ID: 6
[[[369. 389.]
  [497. 387.]
  [500. 513.]
  [372. 517.]]]
[INFO] ArUco marker ID: 8
[[[ 98. 256.]
  [216. 252.]
  [217. 378.]
  [ 97. 380.]]]
[INFO] ArUco marker ID: 3
[[[229. 252.]
  [353. 248.]
  [355. 376.]
  [230. 378.]]]
[INFO] ArUco marker ID: 4
[[[365. 248.]
  [493. 243.]
  [497. 373.]
  [368. 375.]]]
[INFO] ArUco marker ID: 5
[[[104. 124.]
  [222. 120.]
  [217. 239.]
  [ 98. 243.]]]
[INFO] ArUco marker ID: 0
[[[235. 120.]
  [356. 115.]
  [353. 234.]
  [230. 239.]]]
[INFO] ArUco marker ID: 1
[[[368. 114.]
  [491. 106.]
  [493. 230.]
  [366. 234.]]]
[INFO] ArUco marker ID: 2
[[[230. 392.]
  [355. 390.]
  [359. 517.]
  [235. 517.]]]
[INFO] ArUco marker ID: 7
[[[369. 390.]
  [498. 388.]
  [501. 514.]
  [373. 517.]]]
[INFO] ArUco marker ID: 8
[[[ 97. 394.]
  [217. 392.]
  [222. 517.]
  [ 99. 518.]]]
[INFO] ArUco marke

[[[103. 395.]
  [222. 393.]
  [228. 517.]
  [107. 518.]]]
[INFO] ArUco marker ID: 6
[[[235. 393.]
  [358. 390.]
  [364. 516.]
  [241. 516.]]]
[INFO] ArUco marker ID: 7
[[[373. 390.]
  [501. 387.]
  [505. 512.]
  [378. 517.]]]
[INFO] ArUco marker ID: 8
[[[101. 258.]
  [218. 254.]
  [221. 379.]
  [102. 381.]]]
[INFO] ArUco marker ID: 3
[[[231. 253.]
  [355. 249.]
  [358. 376.]
  [234. 379.]]]
[INFO] ArUco marker ID: 4
[[[368. 248.]
  [496. 243.]
  [500. 373.]
  [372. 376.]]]
[INFO] ArUco marker ID: 5
[[[103. 125.]
  [221. 120.]
  [219. 239.]
  [101. 245.]]]
[INFO] ArUco marker ID: 0
[[[235. 120.]
  [356. 115.]
  [354. 235.]
  [231. 239.]]]
[INFO] ArUco marker ID: 1
[[[369. 114.]
  [492. 105.]
  [495. 230.]
  [368. 235.]]]
[INFO] ArUco marker ID: 2
[[[235. 393.]
  [359. 391.]
  [364. 517.]
  [241. 517.]]]
[INFO] ArUco marker ID: 7
[[[103. 395.]
  [221. 393.]
  [228. 517.]
  [107. 519.]]]
[INFO] ArUco marker ID: 6
[[[373. 390.]
  [501. 387.]
  [505. 514.]
  [378. 517.]]]
[INFO] ArUco marke

[[[108. 397.]
  [226. 395.]
  [233. 517.]
  [113. 519.]]]
[INFO] ArUco marker ID: 6
[[[239. 395.]
  [362. 394.]
  [368. 518.]
  [246. 517.]]]
[INFO] ArUco marker ID: 7
[[[376. 393.]
  [504. 391.]
  [508. 516.]
  [381. 518.]]]
[INFO] ArUco marker ID: 8
[[[235. 256.]
  [358. 252.]
  [362. 379.]
  [238. 381.]]]
[INFO] ArUco marker ID: 4
[[[105. 260.]
  [223. 256.]
  [225. 381.]
  [108. 383.]]]
[INFO] ArUco marker ID: 3
[[[371. 251.]
  [499. 247.]
  [504. 377.]
  [375. 380.]]]
[INFO] ArUco marker ID: 5
[[[108. 127.]
  [226. 122.]
  [222. 243.]
  [106. 247.]]]
[INFO] ArUco marker ID: 0
[[[239. 121.]
  [359. 115.]
  [358. 238.]
  [235. 242.]]]
[INFO] ArUco marker ID: 1
[[[372. 114.]
  [496. 105.]
  [499. 233.]
  [372. 238.]]]
[INFO] ArUco marker ID: 2
[[[238. 396.]
  [362. 394.]
  [367. 519.]
  [245. 518.]]]
[INFO] ArUco marker ID: 7
[[[107. 397.]
  [225. 395.]
  [232. 518.]
  [111. 519.]]]
[INFO] ArUco marker ID: 6
[[[376. 394.]
  [504. 391.]
  [508. 517.]
  [381. 520.]]]
[INFO] ArUco marke

[[[246. 393.]
  [369. 393.]
  [374. 517.]
  [251. 515.]]]
[INFO] ArUco marker ID: 7
[[[115. 393.]
  [233. 393.]
  [238. 515.]
  [119. 515.]]]
[INFO] ArUco marker ID: 6
[[[383. 393.]
  [511. 392.]
  [513. 515.]
  [387. 517.]]]
[INFO] ArUco marker ID: 8
[[[244. 254.]
  [367. 252.]
  [369. 379.]
  [247. 380.]]]
[INFO] ArUco marker ID: 4
[[[115. 257.]
  [231. 254.]
  [233. 379.]
  [115. 379.]]]
[INFO] ArUco marker ID: 3
[[[380. 251.]
  [508. 249.]
  [511. 378.]
  [383. 380.]]]
[INFO] ArUco marker ID: 5
[[[120. 124.]
  [236. 121.]
  [232. 241.]
  [115. 243.]]]
[INFO] ArUco marker ID: 0
[[[249. 121.]
  [369. 115.]
  [366. 238.]
  [245. 241.]]]
[INFO] ArUco marker ID: 1
[[[381. 114.]
  [506. 107.]
  [508. 235.]
  [380. 238.]]]
[INFO] ArUco marker ID: 2
[[[246. 393.]
  [369. 393.]
  [374. 517.]
  [251. 515.]]]
[INFO] ArUco marker ID: 7
[[[115. 393.]
  [233. 393.]
  [238. 515.]
  [119. 515.]]]
[INFO] ArUco marker ID: 6
[[[383. 393.]
  [511. 392.]
  [513. 515.]
  [387. 517.]]]
[INFO] ArUco marke

[[[395. 403.]
  [522. 403.]
  [523. 521.]
  [398. 522.]]]
[INFO] ArUco marker ID: 8
[[[257. 400.]
  [380. 402.]
  [385. 521.]
  [265. 517.]]]
[INFO] ArUco marker ID: 7
[[[129. 396.]
  [244. 400.]
  [251. 516.]
  [135. 514.]]]
[INFO] ArUco marker ID: 6
[[[390. 263.]
  [521. 262.]
  [522. 390.]
  [394. 390.]]]
[INFO] ArUco marker ID: 5
[[[252. 262.]
  [375. 262.]
  [380. 389.]
  [257. 387.]]]
[INFO] ArUco marker ID: 4
[[[125. 260.]
  [239. 261.]
  [243. 386.]
  [128. 381.]]]
[INFO] ArUco marker ID: 3
[[[125. 123.]
  [234. 119.]
  [239. 248.]
  [125. 247.]]]
[INFO] ArUco marker ID: 0
[[[247. 118.]
  [371. 115.]
  [376. 248.]
  [251. 248.]]]
[INFO] ArUco marker ID: 1
[[[385. 115.]
  [520. 112.]
  [522. 248.]
  [390. 248.]]]
[INFO] ArUco marker ID: 2
[[[256. 398.]
  [379. 401.]
  [382. 522.]
  [262. 517.]]]
[INFO] ArUco marker ID: 7
[[[393. 402.]
  [521. 403.]
  [521. 524.]
  [396. 524.]]]
[INFO] ArUco marker ID: 8
[[[126. 395.]
  [244. 398.]
  [249. 515.]
  [131. 513.]]]
[INFO] ArUco marke

[[[391. 398.]
  [518. 402.]
  [517. 525.]
  [390. 521.]]]
[INFO] ArUco marker ID: 8
[[[256. 392.]
  [378. 398.]
  [377. 520.]
  [257. 513.]]]
[INFO] ArUco marker ID: 7
[[[126. 388.]
  [243. 392.]
  [243. 513.]
  [125. 508.]]]
[INFO] ArUco marker ID: 6
[[[393. 257.]
  [520. 258.]
  [518. 388.]
  [391. 384.]]]
[INFO] ArUco marker ID: 5
[[[130. 253.]
  [246. 254.]
  [243. 378.]
  [126. 374.]]]
[INFO] ArUco marker ID: 3
[[[259. 254.]
  [380. 257.]
  [378. 383.]
  [255. 379.]]]
[INFO] ArUco marker ID: 4
[[[273. 125.]
  [389. 124.]
  [381. 243.]
  [260. 241.]]]
[INFO] ArUco marker ID: 1
[[[145. 125.]
  [259. 126.]
  [247. 241.]
  [131. 239.]]]
[INFO] ArUco marker ID: 0
[[[402. 124.]
  [524. 120.]
  [520. 245.]
  [394. 243.]]]
[INFO] ArUco marker ID: 2
[[[391. 398.]
  [519. 403.]
  [517. 526.]
  [390. 523.]]]
[INFO] ArUco marker ID: 8
[[[256. 393.]
  [378. 398.]
  [376. 522.]
  [256. 516.]]]
[INFO] ArUco marker ID: 7
[[[125. 388.]
  [242. 392.]
  [242. 515.]
  [124. 509.]]]
[INFO] ArUco marke

[INFO] ArUco marker ID: 0
[[[409. 123.]
  [531. 120.]
  [526. 244.]
  [399. 242.]]]
[INFO] ArUco marker ID: 2
[[[394. 399.]
  [523. 403.]
  [520. 532.]
  [391. 526.]]]
[INFO] ArUco marker ID: 8
[[[258. 392.]
  [381. 399.]
  [377. 526.]
  [256. 517.]]]
[INFO] ArUco marker ID: 7
[[[128. 387.]
  [245. 392.]
  [243. 516.]
  [125. 509.]]]
[INFO] ArUco marker ID: 6
[[[265. 253.]
  [384. 256.]
  [381. 384.]
  [258. 379.]]]
[INFO] ArUco marker ID: 4
[[[398. 256.]
  [526. 258.]
  [522. 390.]
  [394. 384.]]]
[INFO] ArUco marker ID: 5
[[[136. 251.]
  [250. 253.]
  [246. 378.]
  [129. 373.]]]
[INFO] ArUco marker ID: 3
[[[148. 121.]
  [263. 123.]
  [251. 240.]
  [136. 238.]]]
[INFO] ArUco marker ID: 0
[[[408. 121.]
  [530. 118.]
  [526. 244.]
  [398. 242.]]]
[INFO] ArUco marker ID: 2
[[[276. 123.]
  [394. 123.]
  [384. 243.]
  [264. 241.]]]
[INFO] ArUco marker ID: 1
[[[393. 400.]
  [523. 406.]
  [519. 534.]
  [390. 529.]]]
[INFO] ArUco marker ID: 8
[[[258. 393.]
  [380. 400.]
  [376. 527.]
  [255. 

[INFO] ArUco marker ID: 0
[[[390. 405.]
  [520. 413.]
  [515. 542.]
  [386. 535.]]]
[INFO] ArUco marker ID: 8
[[[255. 397.]
  [376. 404.]
  [372. 533.]
  [252. 521.]]]
[INFO] ArUco marker ID: 7
[[[126. 390.]
  [242. 396.]
  [239. 521.]
  [122. 511.]]]
[INFO] ArUco marker ID: 6
[[[261. 258.]
  [382. 261.]
  [377. 390.]
  [254. 383.]]]
[INFO] ArUco marker ID: 4
[[[396. 261.]
  [524. 265.]
  [520. 398.]
  [390. 391.]]]
[INFO] ArUco marker ID: 5
[[[135. 254.]
  [249. 257.]
  [242. 383.]
  [127. 375.]]]
[INFO] ArUco marker ID: 3
[[[408. 126.]
  [531. 124.]
  [524. 251.]
  [396. 248.]]]
[INFO] ArUco marker ID: 2
[[[277. 127.]
  [394. 127.]
  [383. 247.]
  [262. 244.]]]
[INFO] ArUco marker ID: 1
[[[151. 125.]
  [265. 128.]
  [250. 244.]
  [136. 241.]]]
[INFO] ArUco marker ID: 0
[[[389. 406.]
  [519. 412.]
  [514. 543.]
  [385. 535.]]]
[INFO] ArUco marker ID: 8
[[[253. 398.]
  [375. 405.]
  [370. 534.]
  [250. 523.]]]
[INFO] ArUco marker ID: 7
[[[125. 390.]
  [241. 398.]
  [237. 522.]
  [120. 

[[[381. 423.]
  [513. 430.]
  [510. 558.]
  [380. 550.]]]
[INFO] ArUco marker ID: 8
[[[243. 412.]
  [366. 422.]
  [366. 547.]
  [247. 533.]]]
[INFO] ArUco marker ID: 7
[[[126. 397.]
  [231. 411.]
  [234. 531.]
  [128. 514.]]]
[INFO] ArUco marker ID: 6
[[[380. 276.]
  [517. 280.]
  [514. 416.]
  [380. 409.]]]
[INFO] ArUco marker ID: 5
[[[240. 270.]
  [365. 276.]
  [366. 408.]
  [242. 398.]]]
[INFO] ArUco marker ID: 4
[[[126. 262.]
  [228. 270.]
  [230. 397.]
  [127. 384.]]]
[INFO] ArUco marker ID: 3
[[[379. 122.]
  [520. 126.]
  [517. 266.]
  [379. 262.]]]
[INFO] ArUco marker ID: 2
[[[235. 121.]
  [363. 123.]
  [365. 262.]
  [239. 256.]]]
[INFO] ArUco marker ID: 1
[[[125. 123.]
  [223. 123.]
  [226. 256.]
  [125. 248.]]]
[INFO] ArUco marker ID: 0
[[[249. 409.]
  [371. 419.]
  [368. 546.]
  [250. 529.]]]
[INFO] ArUco marker ID: 7
[[[127. 396.]
  [237. 408.]
  [238. 528.]
  [126. 515.]]]
[INFO] ArUco marker ID: 6
[[[386. 274.]
  [521. 279.]
  [516. 414.]
  [384. 406.]]]
[INFO] ArUco marke

[[[100. 256.]
  [174. 208.]
  [208. 330.]
  [125. 372.]]]
[INFO] ArUco marker ID: 3
[[[182. 201.]
  [294. 152.]
  [336. 278.]
  [218. 325.]]]
[INFO] ArUco marker ID: 4
[[[ 89. 275.]
  [159. 213.]
  [212. 329.]
  [131. 388.]]]
[INFO] ArUco marker ID: 3
[[[ 89. 275.]
  [159. 213.]
  [212. 329.]
  [131. 388.]]]
[INFO] ArUco marker ID: 3
[[[ 74. 304.]
  [141. 223.]
  [213. 331.]
  [137. 407.]]]
[INFO] ArUco marker ID: 3
[[[261. 362.]
  [327. 239.]
  [448. 303.]
  [385. 422.]]]
[INFO] ArUco marker ID: 7
[[[261. 362.]
  [327. 239.]
  [448. 303.]
  [385. 422.]]]
[INFO] ArUco marker ID: 7
[[[330. 229.]
  [387. 113.]
  [505. 172.]
  [455. 285.]]]
[INFO] ArUco marker ID: 8
[[[329. 233.]
  [378. 113.]
  [496. 164.]
  [457. 279.]]]
[INFO] ArUco marker ID: 8
[[[329. 236.]
  [368. 115.]
  [490. 157.]
  [460. 275.]]]
[INFO] ArUco marker ID: 8
[[[332. 240.]
  [363. 116.]
  [488. 152.]
  [462. 271.]]]
[INFO] ArUco marker ID: 8
[[[335. 245.]
  [360. 119.]
  [488. 146.]
  [467. 268.]]]
[INFO] ArUco marke

[[[166. 541.]
  [190. 396.]
  [326. 405.]
  [307. 553.]]]
[INFO] ArUco marker ID: 3
[[[ 25. 528.]
  [ 64. 390.]
  [176. 395.]
  [151. 540.]]]
[INFO] ArUco marker ID: 0
[[[343. 390.]
  [358. 258.]
  [488. 272.]
  [480. 401.]]]
[INFO] ArUco marker ID: 7
[[[192. 380.]
  [216. 250.]
  [344. 257.]
  [327. 389.]]]
[INFO] ArUco marker ID: 4
[[[ 67. 375.]
  [ 96. 252.]
  [203. 250.]
  [178. 380.]]]
[INFO] ArUco marker ID: 1
[[[360. 243.]
  [374. 127.]
  [496. 147.]
  [489. 258.]]]
[INFO] ArUco marker ID: 8
[[[218. 237.]
  [238. 119.]
  [361. 125.]
  [345. 243.]]]
[INFO] ArUco marker ID: 5
[[[ 21. 531.]
  [ 60. 391.]
  [178. 400.]
  [153. 544.]]]
[INFO] ArUco marker ID: 0
[[[347. 397.]
  [363. 266.]
  [491. 283.]
  [481. 411.]]]
[INFO] ArUco marker ID: 7
[[[195. 385.]
  [220. 255.]
  [349. 266.]
  [332. 397.]]]
[INFO] ArUco marker ID: 4
[[[ 64. 378.]
  [ 97. 254.]
  [206. 254.]
  [181. 385.]]]
[INFO] ArUco marker ID: 1
[[[365. 251.]
  [380. 132.]
  [499. 151.]
  [491. 269.]]]
[INFO] ArUco marke

[[[165. 451.]
  [270. 447.]
  [266. 548.]
  [160. 554.]]]
[INFO] ArUco marker ID: 8
[[[169. 338.]
  [274. 337.]
  [270. 437.]
  [164. 439.]]]
[INFO] ArUco marker ID: 5
[[[ 46. 336.]
  [157. 337.]
  [152. 439.]
  [ 40. 442.]]]
[INFO] ArUco marker ID: 4
[[[174. 226.]
  [277. 232.]
  [274. 328.]
  [170. 326.]]]
[INFO] ArUco marker ID: 2
[[[ 53. 222.]
  [161. 227.]
  [158. 326.]
  [ 47. 325.]]]
[INFO] ArUco marker ID: 1
[[[169. 342.]
  [273. 342.]
  [270. 440.]
  [164. 444.]]]
[INFO] ArUco marker ID: 5
[[[ 47. 340.]
  [157. 341.]
  [152. 442.]
  [ 41. 445.]]]
[INFO] ArUco marker ID: 4
[[[ 56. 229.]
  [162. 232.]
  [159. 330.]
  [ 50. 329.]]]
[INFO] ArUco marker ID: 1
[[[170. 344.]
  [273. 345.]
  [266. 444.]
  [160. 446.]]]
[INFO] ArUco marker ID: 5
[[[ 47. 342.]
  [157. 344.]
  [148. 446.]
  [ 38. 446.]]]
[INFO] ArUco marker ID: 4
[[[ 46. 342.]
  [154. 346.]
  [145. 446.]
  [ 33. 446.]]]
[INFO] ArUco marker ID: 4
[[[165. 346.]
  [270. 348.]
  [263. 446.]
  [156. 447.]]]
[INFO] ArUco marke

[INFO] ArUco marker ID: 7
[[[328. 434.]
  [422. 429.]
  [420. 521.]
  [327. 534.]]]
[INFO] ArUco marker ID: 8
[[[ 86. 326.]
  [203. 326.]
  [202. 429.]
  [ 82. 435.]]]
[INFO] ArUco marker ID: 3
[[[328. 326.]
  [416. 328.]
  [422. 418.]
  [330. 422.]]]
[INFO] ArUco marker ID: 5
[[[214. 325.]
  [317. 327.]
  [319. 422.]
  [211. 429.]]]
[INFO] ArUco marker ID: 4
[[[214. 226.]
  [311. 237.]
  [317. 316.]
  [215. 315.]]]
[INFO] ArUco marker ID: 1
[[[ 93. 216.]
  [204. 226.]
  [202. 315.]
  [ 90. 314.]]]
[INFO] ArUco marker ID: 0
[[[212. 441.]
  [318. 434.]
  [315. 534.]
  [209. 549.]]]
[INFO] ArUco marker ID: 7
[[[328. 434.]
  [422. 429.]
  [420. 521.]
  [327. 534.]]]
[INFO] ArUco marker ID: 8
[[[ 86. 326.]
  [203. 326.]
  [202. 429.]
  [ 82. 435.]]]
[INFO] ArUco marker ID: 3
[[[328. 326.]
  [416. 328.]
  [422. 418.]
  [330. 422.]]]
[INFO] ArUco marker ID: 5
[[[214. 325.]
  [317. 327.]
  [319. 422.]
  [211. 429.]]]
[INFO] ArUco marker ID: 4
[[[214. 226.]
  [311. 237.]
  [317. 316.]
  [215. 

[[[186. 434.]
  [294. 422.]
  [298. 524.]
  [190. 542.]]]
[INFO] ArUco marker ID: 7
[[[305. 421.]
  [405. 412.]
  [410. 509.]
  [311. 523.]]]
[INFO] ArUco marker ID: 8
[[[ 54. 319.]
  [170. 318.]
  [174. 423.]
  [ 53. 433.]]]
[INFO] ArUco marker ID: 3
[[[182. 317.]
  [288. 312.]
  [293. 410.]
  [185. 422.]]]
[INFO] ArUco marker ID: 4
[[[300. 311.]
  [397. 304.]
  [404. 401.]
  [305. 410.]]]
[INFO] ArUco marker ID: 5
[[[179. 207.]
  [283. 207.]
  [287. 302.]
  [181. 306.]]]
[INFO] ArUco marker ID: 1
[[[ 53. 199.]
  [166. 207.]
  [170. 307.]
  [ 53. 307.]]]
[INFO] ArUco marker ID: 0
[[[184. 433.]
  [292. 423.]
  [296. 525.]
  [187. 542.]]]
[INFO] ArUco marker ID: 7
[[[303. 422.]
  [403. 412.]
  [410. 510.]
  [308. 524.]]]
[INFO] ArUco marker ID: 8
[[[ 51. 318.]
  [168. 318.]
  [171. 422.]
  [ 52. 433.]]]
[INFO] ArUco marker ID: 3
[[[180. 318.]
  [287. 312.]
  [291. 411.]
  [183. 421.]]]
[INFO] ArUco marker ID: 4
[[[298. 311.]
  [395. 303.]
  [403. 401.]
  [303. 410.]]]
[INFO] ArUco marke

[INFO] ArUco marker ID: 7
[[[270. 416.]
  [371. 406.]
  [379. 505.]
  [274. 520.]]]
[INFO] ArUco marker ID: 8
[[[ 12. 313.]
  [133. 312.]
  [135. 416.]
  [ 11. 427.]]]
[INFO] ArUco marker ID: 3
[[[145. 311.]
  [253. 305.]
  [258. 405.]
  [147. 416.]]]
[INFO] ArUco marker ID: 4
[[[265. 305.]
  [364. 296.]
  [371. 395.]
  [269. 404.]]]
[INFO] ArUco marker ID: 5
[[[143. 201.]
  [249. 200.]
  [253. 295.]
  [145. 300.]]]
[INFO] ArUco marker ID: 1
[[[ 13. 193.]
  [130. 200.]
  [132. 300.]
  [ 12. 300.]]]
[INFO] ArUco marker ID: 0
[[[146. 428.]
  [257. 417.]
  [262. 521.]
  [150. 537.]]]
[INFO] ArUco marker ID: 7
[[[268. 417.]
  [370. 406.]
  [377. 506.]
  [273. 520.]]]
[INFO] ArUco marker ID: 8
[[[ 12. 313.]
  [132. 313.]
  [133. 417.]
  [  9. 427.]]]
[INFO] ArUco marker ID: 3
[[[144. 312.]
  [252. 306.]
  [256. 406.]
  [146. 416.]]]
[INFO] ArUco marker ID: 4
[[[263. 305.]
  [362. 296.]
  [369. 395.]
  [268. 405.]]]
[INFO] ArUco marker ID: 5
[[[141. 202.]
  [248. 200.]
  [251. 296.]
  [144. 

[[[154. 429.]
  [262. 418.]
  [267. 520.]
  [158. 537.]]]
[INFO] ArUco marker ID: 7
[[[274. 417.]
  [373. 407.]
  [381. 505.]
  [279. 519.]]]
[INFO] ArUco marker ID: 8
[[[ 21. 315.]
  [138. 314.]
  [141. 418.]
  [ 19. 429.]]]
[INFO] ArUco marker ID: 3
[[[150. 314.]
  [256. 308.]
  [262. 406.]
  [152. 417.]]]
[INFO] ArUco marker ID: 4
[[[268. 308.]
  [364. 298.]
  [372. 396.]
  [273. 405.]]]
[INFO] ArUco marker ID: 5
[[[ 20. 195.]
  [135. 204.]
  [138. 303.]
  [ 21. 303.]]]
[INFO] ArUco marker ID: 0
[[[153. 430.]
  [263. 418.]
  [267. 520.]
  [158. 537.]]]
[INFO] ArUco marker ID: 7
[[[274. 417.]
  [373. 407.]
  [381. 506.]
  [279. 519.]]]
[INFO] ArUco marker ID: 8
[[[ 21. 315.]
  [138. 314.]
  [140. 419.]
  [ 20. 429.]]]
[INFO] ArUco marker ID: 3
[[[150. 314.]
  [257. 308.]
  [262. 406.]
  [153. 417.]]]
[INFO] ArUco marker ID: 4
[[[268. 308.]
  [364. 298.]
  [372. 396.]
  [274. 406.]]]
[INFO] ArUco marker ID: 5
[[[147. 205.]
  [252. 204.]
  [257. 298.]
  [150. 303.]]]
[INFO] ArUco marke

[[[104. 390.]
  [256. 388.]
  [253. 543.]
  [ 96. 545.]]]
[INFO] ArUco marker ID: 6
[[[271. 387.]
  [422. 385.]
  [424. 540.]
  [269. 543.]]]
[INFO] ArUco marker ID: 7
[[[439. 385.]
  [589. 382.]
  [591. 532.]
  [440. 539.]]]
[INFO] ArUco marker ID: 8
[[[112. 226.]
  [259. 224.]
  [256. 371.]
  [105. 373.]]]
[INFO] ArUco marker ID: 3
[[[274. 222.]
  [422. 220.]
  [423. 369.]
  [271. 370.]]]
[INFO] ArUco marker ID: 4
[[[437. 219.]
  [587. 218.]
  [591. 367.]
  [440. 369.]]]
[INFO] ArUco marker ID: 5
[[[118.  70.]
  [260.  66.]
  [260. 207.]
  [113. 209.]]]
[INFO] ArUco marker ID: 0
[[[275.  66.]
  [417.  61.]
  [422. 204.]
  [276. 207.]]]
[INFO] ArUco marker ID: 1
[[[108. 390.]
  [258. 388.]
  [255. 542.]
  [101. 544.]]]
[INFO] ArUco marker ID: 6
[[[274. 388.]
  [424. 386.]
  [426. 539.]
  [272. 542.]]]
[INFO] ArUco marker ID: 7
[[[441. 386.]
  [592. 384.]
  [592. 532.]
  [442. 539.]]]
[INFO] ArUco marker ID: 8
[[[117. 226.]
  [263. 224.]
  [259. 371.]
  [108. 373.]]]
[INFO] ArUco marke

[[[283. 388.]
  [430. 391.]
  [429. 532.]
  [281. 533.]]]
[INFO] ArUco marker ID: 7
[[[446. 391.]
  [594. 394.]
  [590. 536.]
  [444. 534.]]]
[INFO] ArUco marker ID: 8
[[[124. 384.]
  [268. 388.]
  [266. 533.]
  [120. 531.]]]
[INFO] ArUco marker ID: 6
[[[448. 228.]
  [597. 230.]
  [594. 379.]
  [446. 375.]]]
[INFO] ArUco marker ID: 5
[[[289. 226.]
  [433. 228.]
  [430. 375.]
  [283. 371.]]]
[INFO] ArUco marker ID: 4
[[[132. 224.]
  [274. 227.]
  [269. 371.]
  [124. 368.]]]
[INFO] ArUco marker ID: 3
[[[453.  71.]
  [597.  76.]
  [597. 215.]
  [449. 212.]]]
[INFO] ArUco marker ID: 2
[[[293.  67.]
  [437.  71.]
  [433. 213.]
  [289. 211.]]]
[INFO] ArUco marker ID: 1
[[[140.  69.]
  [276.  67.]
  [274. 211.]
  [132. 209.]]]
[INFO] ArUco marker ID: 0
[[[447. 391.]
  [594. 395.]
  [589. 535.]
  [445. 532.]]]
[INFO] ArUco marker ID: 8
[[[284. 388.]
  [430. 391.]
  [429. 532.]
  [282. 532.]]]
[INFO] ArUco marker ID: 7
[[[125. 384.]
  [269. 387.]
  [267. 532.]
  [122. 529.]]]
[INFO] ArUco marke

[[[290. 389.]
  [436. 393.]
  [434. 533.]
  [288. 532.]]]
[INFO] ArUco marker ID: 7
[[[452. 393.]
  [599. 396.]
  [595. 536.]
  [450. 533.]]]
[INFO] ArUco marker ID: 8
[[[132. 385.]
  [275. 389.]
  [273. 533.]
  [128. 530.]]]
[INFO] ArUco marker ID: 6
[[[454. 230.]
  [603. 232.]
  [600. 380.]
  [452. 377.]]]
[INFO] ArUco marker ID: 5
[[[295. 228.]
  [439. 230.]
  [436. 377.]
  [290. 373.]]]
[INFO] ArUco marker ID: 4
[[[140. 226.]
  [280. 228.]
  [276. 373.]
  [132. 369.]]]
[INFO] ArUco marker ID: 3
[[[459.  73.]
  [603.  77.]
  [603. 217.]
  [455. 214.]]]
[INFO] ArUco marker ID: 2
[[[149.  72.]
  [284.  70.]
  [281. 213.]
  [140. 210.]]]
[INFO] ArUco marker ID: 0
[[[299.  69.]
  [444.  72.]
  [439. 215.]
  [296. 213.]]]
[INFO] ArUco marker ID: 1
[[[291. 389.]
  [436. 392.]
  [435. 532.]
  [289. 532.]]]
[INFO] ArUco marker ID: 7
[[[452. 393.]
  [600. 396.]
  [595. 533.]
  [451. 533.]]]
[INFO] ArUco marker ID: 8
[[[132. 385.]
  [276. 389.]
  [273. 532.]
  [128. 530.]]]
[INFO] ArUco marke

[[[453. 393.]
  [601. 397.]
  [596. 536.]
  [450. 533.]]]
[INFO] ArUco marker ID: 8
[[[292. 388.]
  [438. 393.]
  [435. 533.]
  [289. 531.]]]
[INFO] ArUco marker ID: 7
[[[134. 383.]
  [277. 387.]
  [274. 531.]
  [129. 527.]]]
[INFO] ArUco marker ID: 6
[[[298. 227.]
  [442. 230.]
  [437. 377.]
  [292. 372.]]]
[INFO] ArUco marker ID: 4
[[[457. 229.]
  [606. 233.]
  [601. 382.]
  [453. 376.]]]
[INFO] ArUco marker ID: 5
[[[143. 224.]
  [283. 227.]
  [277. 371.]
  [135. 366.]]]
[INFO] ArUco marker ID: 3
[[[464.  73.]
  [607.  78.]
  [606. 218.]
  [458. 214.]]]
[INFO] ArUco marker ID: 2
[[[154.  71.]
  [288.  68.]
  [283. 212.]
  [144. 209.]]]
[INFO] ArUco marker ID: 0
[[[303.  69.]
  [448.  74.]
  [442. 214.]
  [299. 212.]]]
[INFO] ArUco marker ID: 1
[[[453. 393.]
  [601. 397.]
  [596. 536.]
  [450. 533.]]]
[INFO] ArUco marker ID: 8
[[[292. 388.]
  [438. 393.]
  [435. 533.]
  [289. 531.]]]
[INFO] ArUco marker ID: 7
[[[134. 383.]
  [277. 387.]
  [274. 531.]
  [129. 527.]]]
[INFO] ArUco marke

[[[454. 394.]
  [602. 399.]
  [596. 539.]
  [451. 536.]]]
[INFO] ArUco marker ID: 8
[[[292. 388.]
  [438. 394.]
  [435. 534.]
  [289. 532.]]]
[INFO] ArUco marker ID: 7
[[[135. 382.]
  [277. 387.]
  [274. 531.]
  [129. 526.]]]
[INFO] ArUco marker ID: 6
[[[299. 227.]
  [443. 231.]
  [438. 378.]
  [293. 372.]]]
[INFO] ArUco marker ID: 4
[[[459. 230.]
  [608. 235.]
  [602. 384.]
  [454. 378.]]]
[INFO] ArUco marker ID: 5
[[[145. 223.]
  [284. 226.]
  [277. 372.]
  [136. 366.]]]
[INFO] ArUco marker ID: 3
[[[466.  73.]
  [610.  79.]
  [608. 219.]
  [459. 215.]]]
[INFO] ArUco marker ID: 2
[[[305.  69.]
  [450.  73.]
  [443. 215.]
  [300. 212.]]]
[INFO] ArUco marker ID: 1
[[[157.  70.]
  [290.  68.]
  [285. 211.]
  [146. 208.]]]
[INFO] ArUco marker ID: 0
[[[453. 394.]
  [602. 400.]
  [595. 539.]
  [450. 534.]]]
[INFO] ArUco marker ID: 8
[[[292. 387.]
  [437. 393.]
  [434. 534.]
  [288. 531.]]]
[INFO] ArUco marker ID: 7
[[[135. 381.]
  [277. 387.]
  [273. 531.]
  [129. 525.]]]
[INFO] ArUco marke

[[[457. 396.]
  [605. 402.]
  [598. 541.]
  [453. 536.]]]
[INFO] ArUco marker ID: 8
[[[295. 390.]
  [441. 397.]
  [438. 536.]
  [292. 534.]]]
[INFO] ArUco marker ID: 7
[[[137. 384.]
  [280. 390.]
  [276. 533.]
  [132. 529.]]]
[INFO] ArUco marker ID: 6
[[[462. 232.]
  [611. 236.]
  [606. 386.]
  [457. 381.]]]
[INFO] ArUco marker ID: 5
[[[302. 228.]
  [446. 233.]
  [441. 380.]
  [295. 374.]]]
[INFO] ArUco marker ID: 4
[[[147. 224.]
  [286. 228.]
  [279. 374.]
  [138. 368.]]]
[INFO] ArUco marker ID: 3
[[[468.  75.]
  [613.  81.]
  [611. 221.]
  [462. 217.]]]
[INFO] ArUco marker ID: 2
[[[158.  71.]
  [293.  71.]
  [287. 213.]
  [147. 210.]]]
[INFO] ArUco marker ID: 0
[[[308.  70.]
  [453.  76.]
  [446. 217.]
  [302. 213.]]]
[INFO] ArUco marker ID: 1
[[[457. 396.]
  [605. 402.]
  [598. 541.]
  [453. 536.]]]
[INFO] ArUco marker ID: 8
[[[295. 390.]
  [441. 397.]
  [438. 536.]
  [292. 534.]]]
[INFO] ArUco marker ID: 7
[[[137. 384.]
  [280. 390.]
  [276. 533.]
  [132. 529.]]]
[INFO] ArUco marke

[[[453. 395.]
  [602. 401.]
  [594. 541.]
  [449. 535.]]]
[INFO] ArUco marker ID: 8
[[[291. 388.]
  [437. 394.]
  [433. 534.]
  [287. 530.]]]
[INFO] ArUco marker ID: 7
[[[133. 381.]
  [276. 387.]
  [272. 531.]
  [127. 525.]]]
[INFO] ArUco marker ID: 6
[[[298. 226.]
  [443. 231.]
  [437. 378.]
  [291. 371.]]]
[INFO] ArUco marker ID: 4
[[[458. 230.]
  [608. 235.]
  [602. 385.]
  [453. 379.]]]
[INFO] ArUco marker ID: 5
[[[143. 221.]
  [283. 225.]
  [276. 371.]
  [134. 365.]]]
[INFO] ArUco marker ID: 3
[[[465.  73.]
  [612.  79.]
  [609. 219.]
  [459. 215.]]]
[INFO] ArUco marker ID: 2
[[[305.  66.]
  [450.  72.]
  [443. 215.]
  [299. 210.]]]
[INFO] ArUco marker ID: 1
[[[155.  67.]
  [289.  66.]
  [283. 211.]
  [144. 207.]]]
[INFO] ArUco marker ID: 0
[[[452. 395.]
  [601. 401.]
  [593. 540.]
  [448. 534.]]]
[INFO] ArUco marker ID: 8
[[[291. 387.]
  [436. 395.]
  [432. 534.]
  [287. 531.]]]
[INFO] ArUco marker ID: 7
[[[133. 380.]
  [275. 387.]
  [271. 530.]
  [127. 524.]]]
[INFO] ArUco marke

[[[446. 406.]
  [596. 413.]
  [588. 551.]
  [442. 546.]]]
[INFO] ArUco marker ID: 8
[[[284. 398.]
  [430. 405.]
  [426. 545.]
  [280. 541.]]]
[INFO] ArUco marker ID: 7
[[[126. 390.]
  [269. 398.]
  [264. 541.]
  [120. 534.]]]
[INFO] ArUco marker ID: 6
[[[453. 240.]
  [603. 246.]
  [597. 397.]
  [447. 391.]]]
[INFO] ArUco marker ID: 5
[[[292. 235.]
  [437. 241.]
  [429. 390.]
  [284. 382.]]]
[INFO] ArUco marker ID: 4
[[[135. 229.]
  [276. 235.]
  [269. 381.]
  [126. 373.]]]
[INFO] ArUco marker ID: 3
[[[461.  82.]
  [607.  89.]
  [604. 230.]
  [453. 225.]]]
[INFO] ArUco marker ID: 2
[[[149.  75.]
  [285.  75.]
  [277. 219.]
  [136. 214.]]]
[INFO] ArUco marker ID: 0
[[[300.  75.]
  [446.  82.]
  [437. 225.]
  [292. 220.]]]
[INFO] ArUco marker ID: 1
[[[446. 407.]
  [596. 415.]
  [587. 554.]
  [441. 548.]]]
[INFO] ArUco marker ID: 8
[[[283. 399.]
  [429. 407.]
  [424. 548.]
  [278. 544.]]]
[INFO] ArUco marker ID: 7
[[[124. 391.]
  [267. 399.]
  [262. 543.]
  [116. 536.]]]
[INFO] ArUco marke

[[[451. 412.]
  [600. 419.]
  [592. 558.]
  [446. 551.]]]
[INFO] ArUco marker ID: 8
[[[289. 402.]
  [435. 411.]
  [430. 551.]
  [284. 545.]]]
[INFO] ArUco marker ID: 7
[[[131. 394.]
  [274. 403.]
  [268. 546.]
  [125. 539.]]]
[INFO] ArUco marker ID: 6
[[[457. 247.]
  [608. 253.]
  [601. 403.]
  [451. 395.]]]
[INFO] ArUco marker ID: 5
[[[297. 240.]
  [441. 246.]
  [435. 395.]
  [289. 386.]]]
[INFO] ArUco marker ID: 4
[[[141. 234.]
  [281. 240.]
  [274. 386.]
  [132. 378.]]]
[INFO] ArUco marker ID: 3
[[[466.  86.]
  [612.  93.]
  [609. 237.]
  [458. 230.]]]
[INFO] ArUco marker ID: 2
[[[304.  79.]
  [450.  86.]
  [442. 231.]
  [297. 224.]]]
[INFO] ArUco marker ID: 1
[[[151.  78.]
  [288.  79.]
  [283. 225.]
  [142. 219.]]]
[INFO] ArUco marker ID: 0
[[[451. 412.]
  [600. 419.]
  [592. 558.]
  [446. 551.]]]
[INFO] ArUco marker ID: 8
[[[289. 402.]
  [435. 411.]
  [430. 551.]
  [284. 545.]]]
[INFO] ArUco marker ID: 7
[[[131. 394.]
  [274. 403.]
  [268. 546.]
  [125. 539.]]]
[INFO] ArUco marke

[[[316. 337.]
  [468. 343.]
  [465. 492.]
  [315. 485.]]]
[INFO] ArUco marker ID: 7
[[[484. 342.]
  [637. 344.]
  [631. 493.]
  [481. 491.]]]
[INFO] ArUco marker ID: 8
[[[150. 334.]
  [300. 338.]
  [300. 486.]
  [149. 482.]]]
[INFO] ArUco marker ID: 6
[[[487. 171.]
  [644. 175.]
  [638. 329.]
  [484. 325.]]]
[INFO] ArUco marker ID: 5
[[[319. 168.]
  [471. 172.]
  [468. 326.]
  [316. 321.]]]
[INFO] ArUco marker ID: 4
[[[155. 166.]
  [303. 170.]
  [301. 321.]
  [151. 316.]]]
[INFO] ArUco marker ID: 3
[[[486. 346.]
  [640. 349.]
  [635. 495.]
  [484. 495.]]]
[INFO] ArUco marker ID: 8
[[[154. 336.]
  [302. 341.]
  [303. 487.]
  [154. 485.]]]
[INFO] ArUco marker ID: 6
[[[318. 341.]
  [469. 345.]
  [467. 494.]
  [319. 488.]]]
[INFO] ArUco marker ID: 7
[[[489. 173.]
  [646. 177.]
  [641. 332.]
  [488. 330.]]]
[INFO] ArUco marker ID: 5
[[[319. 171.]
  [472. 174.]
  [470. 329.]
  [318. 324.]]]
[INFO] ArUco marker ID: 4
[[[156. 169.]
  [303. 172.]
  [302. 324.]
  [153. 319.]]]
[INFO] ArUco marke

[[[162. 391.]
  [306. 400.]
  [299. 553.]
  [150. 542.]]]
[INFO] ArUco marker ID: 6
[[[499. 237.]
  [658. 245.]
  [650. 401.]
  [492. 394.]]]
[INFO] ArUco marker ID: 5
[[[331. 232.]
  [482. 237.]
  [475. 393.]
  [323. 384.]]]
[INFO] ArUco marker ID: 4
[[[174. 227.]
  [316. 232.]
  [307. 383.]
  [162. 375.]]]
[INFO] ArUco marker ID: 3
[[[188.  69.]
  [325.  67.]
  [317. 216.]
  [175. 212.]]]
[INFO] ArUco marker ID: 0
[[[506.  66.]
  [664.  71.]
  [658. 227.]
  [500. 221.]]]
[INFO] ArUco marker ID: 2
[[[340.  66.]
  [489.  66.]
  [483. 220.]
  [332. 216.]]]
[INFO] ArUco marker ID: 1
[[[162. 392.]
  [309. 398.]
  [303. 552.]
  [154. 543.]]]
[INFO] ArUco marker ID: 6
[[[499. 235.]
  [658. 240.]
  [651. 397.]
  [494. 391.]]]
[INFO] ArUco marker ID: 5
[[[332. 231.]
  [483. 234.]
  [477. 390.]
  [325. 383.]]]
[INFO] ArUco marker ID: 4
[[[175. 227.]
  [317. 231.]
  [309. 382.]
  [164. 375.]]]
[INFO] ArUco marker ID: 3
[[[191.  71.]
  [326.  68.]
  [318. 215.]
  [176. 212.]]]
[INFO] ArUco marke

  [348. 206.]]]
[INFO] ArUco marker ID: 1
[[[219.  55.]
  [349.  59.]
  [332. 206.]
  [197. 193.]]]
[INFO] ArUco marker ID: 0
[[[178. 367.]
  [316. 386.]
  [302. 531.]
  [164. 510.]]]
[INFO] ArUco marker ID: 6
[[[511. 239.]
  [671. 255.]
  [653. 414.]
  [495. 394.]]]
[INFO] ArUco marker ID: 5
[[[349. 222.]
  [496. 237.]
  [479. 391.]
  [332. 371.]]]
[INFO] ArUco marker ID: 4
[[[198. 207.]
  [333. 221.]
  [317. 369.]
  [180. 351.]]]
[INFO] ArUco marker ID: 3
[[[531.  70.]
  [688.  83.]
  [672. 238.]
  [513. 221.]]]
[INFO] ArUco marker ID: 2
[[[367.  60.]
  [515.  69.]
  [497. 220.]
  [350. 207.]]]
[INFO] ArUco marker ID: 1
[[[221.  54.]
  [352.  59.]
  [335. 205.]
  [200. 193.]]]
[INFO] ArUco marker ID: 0
[[[179. 366.]
  [316. 386.]
  [301. 532.]
  [162. 510.]]]
[INFO] ArUco marker ID: 6
[[[514. 239.]
  [673. 256.]
  [655. 416.]
  [496. 395.]]]
[INFO] ArUco marker ID: 5
[[[350. 223.]
  [497. 238.]
  [479. 393.]
  [332. 371.]]]
[INFO] ArUco marker ID: 4
[[[198. 207.]
  [335. 221.]
  [318

[[[178. 252.]
  [319. 242.]
  [327. 395.]
  [184. 401.]]]
[INFO] ArUco marker ID: 3
[[[335. 242.]
  [487. 232.]
  [495. 390.]
  [343. 395.]]]
[INFO] ArUco marker ID: 4
[[[504. 231.]
  [664. 222.]
  [672. 382.]
  [512. 389.]]]
[INFO] ArUco marker ID: 5
[[[176.  90.]
  [312.  72.]
  [317. 227.]
  [178. 236.]]]
[INFO] ArUco marker ID: 0
[[[327.  72.]
  [479.  58.]
  [487. 215.]
  [334. 226.]]]
[INFO] ArUco marker ID: 1
[[[496.  58.]
  [658.  47.]
  [664. 206.]
  [503. 214.]]]
[INFO] ArUco marker ID: 2
[[[178. 252.]
  [319. 242.]
  [327. 395.]
  [184. 401.]]]
[INFO] ArUco marker ID: 3
[[[335. 242.]
  [487. 232.]
  [495. 390.]
  [343. 395.]]]
[INFO] ArUco marker ID: 4
[[[504. 231.]
  [664. 222.]
  [672. 382.]
  [512. 389.]]]
[INFO] ArUco marker ID: 5
[[[176.  90.]
  [312.  72.]
  [317. 227.]
  [178. 236.]]]
[INFO] ArUco marker ID: 0
[[[327.  72.]
  [479.  58.]
  [487. 215.]
  [334. 226.]]]
[INFO] ArUco marker ID: 1
[[[496.  58.]
  [658.  47.]
  [664. 206.]
  [503. 214.]]]
[INFO] ArUco marke

[[[172. 242.]
  [317. 228.]
  [324. 387.]
  [176. 393.]]]
[INFO] ArUco marker ID: 3
[[[333. 228.]
  [488. 214.]
  [499. 376.]
  [342. 385.]]]
[INFO] ArUco marker ID: 4
[[[505. 215.]
  [670. 199.]
  [683. 365.]
  [517. 377.]]]
[INFO] ArUco marker ID: 5
[[[494.  45.]
  [654.  29.]
  [668. 183.]
  [504. 198.]]]
[INFO] ArUco marker ID: 2
[[[342. 395.]
  [502. 389.]
  [511. 556.]
  [350. 557.]]]
[INFO] ArUco marker ID: 7
[[[519. 390.]
  [689. 380.]
  [699. 550.]
  [529. 556.]]]
[INFO] ArUco marker ID: 8
[[[174. 234.]
  [319. 222.]
  [325. 379.]
  [177. 387.]]]
[INFO] ArUco marker ID: 3
[[[335. 221.]
  [491. 208.]
  [500. 372.]
  [341. 379.]]]
[INFO] ArUco marker ID: 4
[[[509. 207.]
  [677. 195.]
  [687. 361.]
  [519. 372.]]]
[INFO] ArUco marker ID: 5
[[[173.  77.]
  [311.  52.]
  [316. 207.]
  [173. 221.]]]
[INFO] ArUco marker ID: 0
[[[342. 391.]
  [503. 385.]
  [512. 553.]
  [349. 554.]]]
[INFO] ArUco marker ID: 7
[[[175. 395.]
  [325. 391.]
  [332. 553.]
  [177. 557.]]]
[INFO] ArUco marke

[[[164. 385.]
  [320. 383.]
  [325. 553.]
  [166. 551.]]]
[INFO] ArUco marker ID: 6
[[[166. 204.]
  [316. 195.]
  [319. 364.]
  [165. 367.]]]
[INFO] ArUco marker ID: 3
[[[333. 195.]
  [500. 184.]
  [505. 362.]
  [336. 364.]]]
[INFO] ArUco marker ID: 4
[[[519. 183.]
  [702. 173.]
  [708. 358.]
  [524. 362.]]]
[INFO] ArUco marker ID: 5
[[[173.  36.]
  [314.  13.]
  [317. 177.]
  [167. 188.]]]
[INFO] ArUco marker ID: 0
[[[164. 387.]
  [319. 384.]
  [326. 553.]
  [166. 552.]]]
[INFO] ArUco marker ID: 6
[[[166. 205.]
  [317. 197.]
  [320. 365.]
  [165. 368.]]]
[INFO] ArUco marker ID: 3
[[[334. 196.]
  [500. 186.]
  [506. 364.]
  [337. 366.]]]
[INFO] ArUco marker ID: 4
[[[519. 185.]
  [703. 175.]
  [709. 361.]
  [525. 364.]]]
[INFO] ArUco marker ID: 5
[[[173.  35.]
  [314.  14.]
  [317. 180.]
  [167. 189.]]]
[INFO] ArUco marker ID: 0
[[[164. 387.]
  [319. 384.]
  [326. 553.]
  [166. 552.]]]
[INFO] ArUco marker ID: 6
[[[166. 205.]
  [317. 197.]
  [320. 365.]
  [165. 368.]]]
[INFO] ArUco marke

[[[462. 406.]
  [600. 410.]
  [598. 551.]
  [460. 543.]]]
[INFO] ArUco marker ID: 8
[[[319. 400.]
  [449. 406.]
  [444. 542.]
  [317. 532.]]]
[INFO] ArUco marker ID: 7
[[[185. 396.]
  [306. 400.]
  [303. 531.]
  [179. 526.]]]
[INFO] ArUco marker ID: 6
[[[323. 255.]
  [451. 255.]
  [449. 390.]
  [319. 386.]]]
[INFO] ArUco marker ID: 4
[[[193. 255.]
  [310. 255.]
  [306. 386.]
  [186. 382.]]]
[INFO] ArUco marker ID: 3
[[[466. 255.]
  [603. 256.]
  [599. 395.]
  [462. 390.]]]
[INFO] ArUco marker ID: 5
[[[200. 119.]
  [314. 114.]
  [311. 241.]
  [193. 241.]]]
[INFO] ArUco marker ID: 0
[[[470. 110.]
  [603. 109.]
  [603. 240.]
  [466. 241.]]]
[INFO] ArUco marker ID: 2
[[[327. 112.]
  [456. 110.]
  [450. 241.]
  [324. 242.]]]
[INFO] ArUco marker ID: 1
[[[458. 405.]
  [594. 410.]
  [593. 548.]
  [455. 541.]]]
[INFO] ArUco marker ID: 8
[[[318. 400.]
  [444. 405.]
  [441. 541.]
  [315. 531.]]]
[INFO] ArUco marker ID: 7
[[[187. 395.]
  [305. 399.]
  [301. 530.]
  [180. 522.]]]
[INFO] ArUco marke

[[[446. 401.]
  [577. 408.]
  [574. 546.]
  [439. 535.]]]
[INFO] ArUco marker ID: 8
[[[311. 394.]
  [432. 401.]
  [426. 534.]
  [304. 522.]]]
[INFO] ArUco marker ID: 7
[[[185. 388.]
  [298. 393.]
  [291. 522.]
  [174. 512.]]]
[INFO] ArUco marker ID: 6
[[[321. 256.]
  [439. 257.]
  [432. 386.]
  [311. 380.]]]
[INFO] ArUco marker ID: 4
[[[200. 255.]
  [309. 256.]
  [298. 380.]
  [187. 375.]]]
[INFO] ArUco marker ID: 3
[[[453. 257.]
  [582. 259.]
  [578. 393.]
  [446. 387.]]]
[INFO] ArUco marker ID: 5
[[[465. 132.]
  [587. 132.]
  [582. 244.]
  [453. 244.]]]
[INFO] ArUco marker ID: 2
[[[336. 131.]
  [452. 131.]
  [440. 244.]
  [322. 243.]]]
[INFO] ArUco marker ID: 1
[[[215. 131.]
  [324. 131.]
  [309. 244.]
  [201. 243.]]]
[INFO] ArUco marker ID: 0
[[[446. 401.]
  [577. 408.]
  [574. 546.]
  [439. 535.]]]
[INFO] ArUco marker ID: 8
[[[311. 394.]
  [432. 401.]
  [426. 534.]
  [304. 522.]]]
[INFO] ArUco marker ID: 7
[[[185. 388.]
  [298. 393.]
  [291. 522.]
  [174. 512.]]]
[INFO] ArUco marke

[[[438. 396.]
  [570. 402.]
  [568. 540.]
  [433. 531.]]]
[INFO] ArUco marker ID: 8
[[[304. 390.]
  [424. 395.]
  [419. 529.]
  [298. 518.]]]
[INFO] ArUco marker ID: 7
[[[179. 385.]
  [291. 389.]
  [286. 517.]
  [170. 509.]]]
[INFO] ArUco marker ID: 6
[[[313. 251.]
  [431. 252.]
  [425. 381.]
  [304. 375.]]]
[INFO] ArUco marker ID: 4
[[[445. 251.]
  [573. 251.]
  [570. 387.]
  [438. 381.]]]
[INFO] ArUco marker ID: 5
[[[192. 252.]
  [301. 252.]
  [292. 375.]
  [181. 371.]]]
[INFO] ArUco marker ID: 3
[[[207. 128.]
  [317. 127.]
  [302. 239.]
  [193. 239.]]]
[INFO] ArUco marker ID: 0
[[[457. 126.]
  [580. 125.]
  [574. 237.]
  [445. 238.]]]
[INFO] ArUco marker ID: 2
[[[329. 126.]
  [444. 125.]
  [432. 238.]
  [314. 238.]]]
[INFO] ArUco marker ID: 1
[[[438. 396.]
  [570. 401.]
  [568. 540.]
  [433. 530.]]]
[INFO] ArUco marker ID: 8
[[[304. 389.]
  [424. 395.]
  [419. 529.]
  [298. 518.]]]
[INFO] ArUco marker ID: 7
[[[179. 385.]
  [291. 389.]
  [285. 517.]
  [169. 509.]]]
[INFO] ArUco marke

[[[436. 399.]
  [569. 406.]
  [566. 547.]
  [429. 536.]]]
[INFO] ArUco marker ID: 8
[[[301. 392.]
  [422. 399.]
  [416. 535.]
  [294. 521.]]]
[INFO] ArUco marker ID: 7
[[[177. 386.]
  [289. 392.]
  [281. 522.]
  [166. 511.]]]
[INFO] ArUco marker ID: 6
[[[312. 253.]
  [430. 254.]
  [423. 384.]
  [302. 378.]]]
[INFO] ArUco marker ID: 4
[[[444. 253.]
  [573. 253.]
  [570. 390.]
  [437. 385.]]]
[INFO] ArUco marker ID: 5
[[[192. 253.]
  [300. 253.]
  [290. 377.]
  [178. 372.]]]
[INFO] ArUco marker ID: 3
[[[208. 128.]
  [316. 127.]
  [300. 241.]
  [193. 241.]]]
[INFO] ArUco marker ID: 0
[[[329. 126.]
  [444. 127.]
  [430. 241.]
  [313. 241.]]]
[INFO] ArUco marker ID: 1
[[[457. 126.]
  [580. 125.]
  [574. 240.]
  [444. 240.]]]
[INFO] ArUco marker ID: 2
[[[436. 399.]
  [569. 406.]
  [565. 547.]
  [429. 536.]]]
[INFO] ArUco marker ID: 8
[[[301. 392.]
  [422. 399.]
  [415. 534.]
  [294. 522.]]]
[INFO] ArUco marker ID: 7
[[[177. 386.]
  [289. 392.]
  [281. 521.]
  [166. 511.]]]
[INFO] ArUco marke

[[[433. 400.]
  [562. 407.]
  [557. 551.]
  [423. 538.]]]
[INFO] ArUco marker ID: 8
[[[313. 393.]
  [420. 399.]
  [409. 535.]
  [295. 520.]]]
[INFO] ArUco marker ID: 7
[[[191. 384.]
  [302. 393.]
  [284. 519.]
  [171. 507.]]]
[INFO] ArUco marker ID: 6
[[[212. 257.]
  [320. 264.]
  [304. 379.]
  [192. 371.]]]
[INFO] ArUco marker ID: 3
[[[446. 257.]
  [568. 254.]
  [563. 391.]
  [434. 385.]]]
[INFO] ArUco marker ID: 5
[[[230. 139.]
  [334. 142.]
  [321. 250.]
  [213. 245.]]]
[INFO] ArUco marker ID: 0
[[[464. 133.]
  [581. 126.]
  [568. 241.]
  [447. 243.]]]
[INFO] ArUco marker ID: 2
[[[436. 402.]
  [559. 408.]
  [553. 555.]
  [425. 538.]]]
[INFO] ArUco marker ID: 8
[[[317. 395.]
  [426. 403.]
  [412. 536.]
  [297. 520.]]]
[INFO] ArUco marker ID: 7
[[[190. 385.]
  [305. 394.]
  [286. 520.]
  [168. 507.]]]
[INFO] ArUco marker ID: 6
[[[335. 265.]
  [440. 265.]
  [428. 388.]
  [319. 381.]]]
[INFO] ArUco marker ID: 4
[[[212. 258.]
  [324. 266.]
  [308. 381.]
  [192. 371.]]]
[INFO] ArUco marke

[[[441. 404.]
  [558. 410.]
  [554. 555.]
  [428. 538.]]]
[INFO] ArUco marker ID: 8
[[[320. 395.]
  [429. 403.]
  [416. 536.]
  [300. 522.]]]
[INFO] ArUco marker ID: 7
[[[191. 385.]
  [307. 395.]
  [288. 520.]
  [169. 508.]]]
[INFO] ArUco marker ID: 6
[[[339. 268.]
  [441. 266.]
  [430. 389.]
  [322. 383.]]]
[INFO] ArUco marker ID: 4
[[[215. 259.]
  [327. 268.]
  [309. 382.]
  [194. 372.]]]
[INFO] ArUco marker ID: 3
[[[452. 266.]
  [564. 258.]
  [559. 394.]
  [442. 390.]]]
[INFO] ArUco marker ID: 5
[[[239. 144.]
  [345. 152.]
  [330. 256.]
  [218. 247.]]]
[INFO] ArUco marker ID: 0
[[[357. 151.]
  [455. 142.]
  [442. 254.]
  [341. 256.]]]
[INFO] ArUco marker ID: 1
[[[465. 141.]
  [577. 126.]
  [565. 244.]
  [454. 253.]]]
[INFO] ArUco marker ID: 2
[[[441. 403.]
  [557. 409.]
  [553. 555.]
  [427. 537.]]]
[INFO] ArUco marker ID: 8
[[[320. 395.]
  [428. 403.]
  [414. 536.]
  [300. 521.]]]
[INFO] ArUco marker ID: 7
[[[191. 385.]
  [307. 395.]
  [287. 520.]
  [168. 507.]]]
[INFO] ArUco marke

[[[439. 404.]
  [556. 410.]
  [552. 556.]
  [426. 539.]]]
[INFO] ArUco marker ID: 8
[[[318. 395.]
  [427. 403.]
  [413. 536.]
  [296. 522.]]]
[INFO] ArUco marker ID: 7
[[[190. 384.]
  [306. 395.]
  [284. 520.]
  [166. 507.]]]
[INFO] ArUco marker ID: 6
[[[338. 268.]
  [440. 266.]
  [428. 389.]
  [319. 383.]]]
[INFO] ArUco marker ID: 4
[[[216. 258.]
  [326. 268.]
  [308. 381.]
  [192. 371.]]]
[INFO] ArUco marker ID: 3
[[[451. 265.]
  [562. 257.]
  [557. 394.]
  [441. 390.]]]
[INFO] ArUco marker ID: 5
[[[239. 145.]
  [345. 153.]
  [328. 256.]
  [218. 247.]]]
[INFO] ArUco marker ID: 0
[[[356. 152.]
  [454. 142.]
  [440. 254.]
  [340. 256.]]]
[INFO] ArUco marker ID: 1
[[[465. 140.]
  [575. 126.]
  [563. 244.]
  [453. 253.]]]
[INFO] ArUco marker ID: 2
[[[439. 404.]
  [556. 410.]
  [552. 556.]
  [425. 538.]]]
[INFO] ArUco marker ID: 8
[[[317. 396.]
  [427. 403.]
  [412. 537.]
  [297. 522.]]]
[INFO] ArUco marker ID: 7
[[[190. 384.]
  [305. 395.]
  [284. 520.]
  [166. 507.]]]
[INFO] ArUco marke

[[[442. 402.]
  [560. 408.]
  [557. 554.]
  [429. 537.]]]
[INFO] ArUco marker ID: 8
[[[319. 395.]
  [429. 402.]
  [415. 536.]
  [299. 521.]]]
[INFO] ArUco marker ID: 7
[[[192. 384.]
  [307. 393.]
  [287. 519.]
  [169. 507.]]]
[INFO] ArUco marker ID: 6
[[[339. 266.]
  [442. 264.]
  [431. 388.]
  [322. 381.]]]
[INFO] ArUco marker ID: 4
[[[453. 264.]
  [566. 256.]
  [561. 393.]
  [443. 388.]]]
[INFO] ArUco marker ID: 5
[[[218. 258.]
  [328. 266.]
  [310. 380.]
  [195. 371.]]]
[INFO] ArUco marker ID: 3
[[[241. 144.]
  [347. 151.]
  [329. 255.]
  [220. 246.]]]
[INFO] ArUco marker ID: 0
[[[357. 150.]
  [456. 140.]
  [443. 252.]
  [341. 254.]]]
[INFO] ArUco marker ID: 1
[[[442. 403.]
  [561. 409.]
  [556. 555.]
  [428. 537.]]]
[INFO] ArUco marker ID: 8
[[[319. 395.]
  [429. 402.]
  [416. 536.]
  [300. 521.]]]
[INFO] ArUco marker ID: 7
[[[192. 384.]
  [307. 394.]
  [287. 520.]
  [169. 507.]]]
[INFO] ArUco marker ID: 6
[[[340. 267.]
  [442. 265.]
  [431. 388.]
  [321. 381.]]]
[INFO] ArUco marke

[[[442. 405.]
  [561. 411.]
  [557. 557.]
  [429. 540.]]]
[INFO] ArUco marker ID: 8
[[[320. 397.]
  [430. 404.]
  [416. 538.]
  [300. 524.]]]
[INFO] ArUco marker ID: 7
[[[193. 386.]
  [308. 396.]
  [287. 522.]
  [169. 509.]]]
[INFO] ArUco marker ID: 6
[[[341. 269.]
  [443. 267.]
  [431. 390.]
  [322. 383.]]]
[INFO] ArUco marker ID: 4
[[[219. 260.]
  [330. 269.]
  [310. 383.]
  [195. 372.]]]
[INFO] ArUco marker ID: 3
[[[454. 266.]
  [567. 258.]
  [562. 395.]
  [443. 390.]]]
[INFO] ArUco marker ID: 5
[[[244. 146.]
  [349. 153.]
  [331. 257.]
  [221. 248.]]]
[INFO] ArUco marker ID: 0
[[[360. 153.]
  [458. 143.]
  [445. 254.]
  [343. 257.]]]
[INFO] ArUco marker ID: 1
[[[469. 141.]
  [581. 128.]
  [568. 245.]
  [456. 253.]]]
[INFO] ArUco marker ID: 2
[[[443. 404.]
  [561. 410.]
  [557. 557.]
  [428. 539.]]]
[INFO] ArUco marker ID: 8
[[[320. 397.]
  [430. 404.]
  [416. 538.]
  [299. 523.]]]
[INFO] ArUco marker ID: 7
[[[193. 385.]
  [308. 396.]
  [287. 522.]
  [168. 509.]]]
[INFO] ArUco marke

[[[446. 394.]
  [569. 400.]
  [564. 545.]
  [432. 529.]]]
[INFO] ArUco marker ID: 8
[[[318. 387.]
  [432. 393.]
  [419. 528.]
  [298. 513.]]]
[INFO] ArUco marker ID: 7
[[[189. 377.]
  [305. 385.]
  [284. 513.]
  [168. 501.]]]
[INFO] ArUco marker ID: 6
[[[215. 250.]
  [326. 259.]
  [307. 373.]
  [192. 362.]]]
[INFO] ArUco marker ID: 3
[[[339. 257.]
  [445. 256.]
  [432. 380.]
  [321. 374.]]]
[INFO] ArUco marker ID: 4
[[[457. 255.]
  [574. 248.]
  [570. 384.]
  [446. 380.]]]
[INFO] ArUco marker ID: 5
[[[239. 137.]
  [342. 141.]
  [327. 246.]
  [218. 238.]]]
[INFO] ArUco marker ID: 0
[[[446. 391.]
  [574. 399.]
  [567. 543.]
  [433. 527.]]]
[INFO] ArUco marker ID: 8
[[[314. 381.]
  [432. 391.]
  [419. 525.]
  [297. 511.]]]
[INFO] ArUco marker ID: 7
[[[187. 373.]
  [302. 382.]
  [284. 510.]
  [168. 498.]]]
[INFO] ArUco marker ID: 6
[[[334. 251.]
  [445. 251.]
  [434. 376.]
  [317. 367.]]]
[INFO] ArUco marker ID: 4
[[[458. 250.]
  [580. 247.]
  [574. 383.]
  [447. 376.]]]
[INFO] ArUco marke

[INFO] ArUco marker ID: 2
[[[348.  90.]
  [463.  92.]
  [445. 224.]
  [328. 212.]]]
[INFO] ArUco marker ID: 1
[[[242.  89.]
  [339.  91.]
  [317. 211.]
  [216. 200.]]]
[INFO] ArUco marker ID: 0
[[[439. 387.]
  [575. 405.]
  [558. 546.]
  [421. 523.]]]
[INFO] ArUco marker ID: 8
[[[306. 365.]
  [426. 384.]
  [408. 519.]
  [289. 494.]]]
[INFO] ArUco marker ID: 7
[[[189. 347.]
  [294. 364.]
  [278. 492.]
  [167. 469.]]]
[INFO] ArUco marker ID: 6
[[[459. 237.]
  [592. 250.]
  [575. 391.]
  [441. 371.]]]
[INFO] ArUco marker ID: 5
[[[326. 225.]
  [444. 236.]
  [427. 369.]
  [307. 351.]]]
[INFO] ArUco marker ID: 4
[[[214. 215.]
  [314. 224.]
  [295. 349.]
  [192. 334.]]]
[INFO] ArUco marker ID: 3
[[[476.  92.]
  [610. 101.]
  [593. 237.]
  [460. 223.]]]
[INFO] ArUco marker ID: 2
[[[346.  89.]
  [463.  92.]
  [446. 223.]
  [328. 211.]]]
[INFO] ArUco marker ID: 1
[[[239.  90.]
  [335.  89.]
  [315. 211.]
  [216. 202.]]]
[INFO] ArUco marker ID: 0
[[[309. 365.]
  [429. 381.]
  [415. 516.]
  [295. 

[[[453. 368.]
  [589. 374.]
  [585. 517.]
  [448. 504.]]]
[INFO] ArUco marker ID: 8
[[[319. 361.]
  [439. 367.]
  [434. 503.]
  [312. 490.]]]
[INFO] ArUco marker ID: 7
[[[198. 356.]
  [307. 361.]
  [300. 489.]
  [186. 480.]]]
[INFO] ArUco marker ID: 6
[[[212. 224.]
  [317. 222.]
  [308. 346.]
  [200. 343.]]]
[INFO] ArUco marker ID: 3
[[[329. 222.]
  [446. 220.]
  [440. 352.]
  [320. 347.]]]
[INFO] ArUco marker ID: 4
[[[461. 219.]
  [592. 218.]
  [589. 359.]
  [454. 353.]]]
[INFO] ArUco marker ID: 5
[[[232. 103.]
  [330.  92.]
  [319. 209.]
  [215. 212.]]]
[INFO] ArUco marker ID: 0
[[[341.  92.]
  [453.  80.]
  [447. 206.]
  [330. 209.]]]
[INFO] ArUco marker ID: 1
[[[467.  79.]
  [597.  74.]
  [593. 204.]
  [461. 206.]]]
[INFO] ArUco marker ID: 2
[[[452. 367.]
  [588. 373.]
  [585. 517.]
  [446. 506.]]]
[INFO] ArUco marker ID: 8
[[[317. 361.]
  [438. 367.]
  [432. 504.]
  [310. 491.]]]
[INFO] ArUco marker ID: 7
[[[196. 356.]
  [305. 360.]
  [297. 490.]
  [182. 480.]]]
[INFO] ArUco marke

[[[321. 357.]
  [441. 362.]
  [438. 497.]
  [316. 486.]]]
[INFO] ArUco marker ID: 7
[[[455. 362.]
  [590. 366.]
  [589. 508.]
  [451. 498.]]]
[INFO] ArUco marker ID: 8
[[[201. 354.]
  [308. 357.]
  [304. 486.]
  [191. 478.]]]
[INFO] ArUco marker ID: 6
[[[213. 223.]
  [317. 219.]
  [309. 343.]
  [202. 340.]]]
[INFO] ArUco marker ID: 3
[[[328. 219.]
  [444. 214.]
  [441. 347.]
  [322. 344.]]]
[INFO] ArUco marker ID: 4
[[[458. 214.]
  [591. 210.]
  [590. 351.]
  [455. 347.]]]
[INFO] ArUco marker ID: 5
[[[230. 101.]
  [327.  88.]
  [318. 206.]
  [215. 210.]]]
[INFO] ArUco marker ID: 0
[[[338.  87.]
  [449.  74.]
  [445. 201.]
  [329. 205.]]]
[INFO] ArUco marker ID: 1
[[[462.  73.]
  [593.  63.]
  [591. 196.]
  [459. 200.]]]
[INFO] ArUco marker ID: 2
[[[321. 357.]
  [441. 362.]
  [437. 498.]
  [316. 487.]]]
[INFO] ArUco marker ID: 7
[[[455. 362.]
  [591. 366.]
  [589. 508.]
  [451. 499.]]]
[INFO] ArUco marker ID: 8
[[[201. 354.]
  [308. 357.]
  [303. 486.]
  [190. 478.]]]
[INFO] ArUco marke

[[[454. 362.]
  [590. 366.]
  [588. 510.]
  [449. 499.]]]
[INFO] ArUco marker ID: 8
[[[200. 354.]
  [308. 357.]
  [301. 487.]
  [186. 479.]]]
[INFO] ArUco marker ID: 6
[[[320. 357.]
  [441. 362.]
  [434. 499.]
  [314. 488.]]]
[INFO] ArUco marker ID: 7
[[[216. 223.]
  [320. 220.]
  [309. 343.]
  [202. 341.]]]
[INFO] ArUco marker ID: 3
[[[331. 220.]
  [447. 215.]
  [441. 347.]
  [322. 344.]]]
[INFO] ArUco marker ID: 4
[[[461. 215.]
  [592. 211.]
  [590. 351.]
  [455. 347.]]]
[INFO] ArUco marker ID: 5
[[[241. 108.]
  [338.  97.]
  [321. 207.]
  [218. 211.]]]
[INFO] ArUco marker ID: 0
[[[348.  96.]
  [457.  82.]
  [449. 201.]
  [334. 207.]]]
[INFO] ArUco marker ID: 1
[[[470.  80.]
  [595.  68.]
  [593. 196.]
  [463. 202.]]]
[INFO] ArUco marker ID: 2
[[[320. 357.]
  [441. 362.]
  [436. 498.]
  [314. 488.]]]
[INFO] ArUco marker ID: 7
[[[455. 361.]
  [590. 366.]
  [588. 510.]
  [449. 499.]]]
[INFO] ArUco marker ID: 8
[[[200. 354.]
  [309. 358.]
  [301. 487.]
  [187. 479.]]]
[INFO] ArUco marke

[[[454. 363.]
  [590. 367.]
  [588. 511.]
  [449. 501.]]]
[INFO] ArUco marker ID: 8
[[[198. 355.]
  [307. 359.]
  [299. 489.]
  [183. 480.]]]
[INFO] ArUco marker ID: 6
[[[320. 358.]
  [440. 362.]
  [435. 500.]
  [312. 490.]]]
[INFO] ArUco marker ID: 7
[[[214. 225.]
  [317. 220.]
  [308. 344.]
  [200. 342.]]]
[INFO] ArUco marker ID: 3
[[[330. 220.]
  [447. 216.]
  [441. 348.]
  [321. 345.]]]
[INFO] ArUco marker ID: 4
[[[460. 215.]
  [592. 212.]
  [590. 352.]
  [455. 348.]]]
[INFO] ArUco marker ID: 5
[[[239. 109.]
  [335.  96.]
  [320. 208.]
  [217. 212.]]]
[INFO] ArUco marker ID: 0
[[[346.  95.]
  [456.  82.]
  [447. 203.]
  [332. 207.]]]
[INFO] ArUco marker ID: 1
[[[468.  81.]
  [595.  67.]
  [592. 198.]
  [461. 202.]]]
[INFO] ArUco marker ID: 2
[[[454. 363.]
  [589. 368.]
  [587. 512.]
  [448. 501.]]]
[INFO] ArUco marker ID: 8
[[[319. 358.]
  [440. 363.]
  [434. 500.]
  [313. 489.]]]
[INFO] ArUco marker ID: 7
[[[198. 355.]
  [307. 358.]
  [300. 488.]
  [185. 479.]]]
[INFO] ArUco marke

[[[452. 368.]
  [589. 374.]
  [585. 520.]
  [446. 508.]]]
[INFO] ArUco marker ID: 8
[[[318. 362.]
  [438. 368.]
  [431. 507.]
  [309. 494.]]]
[INFO] ArUco marker ID: 7
[[[196. 358.]
  [305. 362.]
  [297. 493.]
  [181. 483.]]]
[INFO] ArUco marker ID: 6
[[[214. 227.]
  [319. 225.]
  [307. 348.]
  [198. 344.]]]
[INFO] ArUco marker ID: 3
[[[331. 224.]
  [447. 221.]
  [439. 353.]
  [318. 348.]]]
[INFO] ArUco marker ID: 4
[[[461. 221.]
  [592. 218.]
  [589. 358.]
  [453. 354.]]]
[INFO] ArUco marker ID: 5
[[[242. 114.]
  [342. 107.]
  [321. 212.]
  [216. 214.]]]
[INFO] ArUco marker ID: 0
[[[354. 106.]
  [462.  95.]
  [448. 208.]
  [332. 211.]]]
[INFO] ArUco marker ID: 1
[[[475.  92.]
  [598.  81.]
  [592. 204.]
  [462. 208.]]]
[INFO] ArUco marker ID: 2
[[[454. 371.]
  [590. 377.]
  [587. 522.]
  [447. 510.]]]
[INFO] ArUco marker ID: 8
[[[319. 365.]
  [440. 371.]
  [433. 509.]
  [312. 497.]]]
[INFO] ArUco marker ID: 7
[[[197. 360.]
  [306. 365.]
  [299. 495.]
  [183. 486.]]]
[INFO] ArUco marke

[[[451. 373.]
  [588. 379.]
  [585. 524.]
  [445. 512.]]]
[INFO] ArUco marker ID: 8
[[[196. 361.]
  [304. 366.]
  [297. 496.]
  [182. 487.]]]
[INFO] ArUco marker ID: 6
[[[317. 366.]
  [437. 372.]
  [431. 511.]
  [309. 498.]]]
[INFO] ArUco marker ID: 7
[[[213. 229.]
  [318. 228.]
  [304. 352.]
  [197. 348.]]]
[INFO] ArUco marker ID: 3
[[[329. 227.]
  [446. 225.]
  [438. 357.]
  [317. 352.]]]
[INFO] ArUco marker ID: 4
[[[459. 224.]
  [591. 222.]
  [588. 363.]
  [452. 358.]]]
[INFO] ArUco marker ID: 5
[[[239. 114.]
  [342. 110.]
  [319. 215.]
  [215. 217.]]]
[INFO] ArUco marker ID: 0
[[[353. 109.]
  [463.  99.]
  [447. 212.]
  [331. 214.]]]
[INFO] ArUco marker ID: 1
[[[475.  96.]
  [599.  85.]
  [591. 208.]
  [461. 211.]]]
[INFO] ArUco marker ID: 2
[[[452. 373.]
  [588. 379.]
  [585. 523.]
  [446. 512.]]]
[INFO] ArUco marker ID: 8
[[[316. 367.]
  [437. 373.]
  [432. 511.]
  [309. 499.]]]
[INFO] ArUco marker ID: 7
[[[195. 363.]
  [304. 367.]
  [296. 498.]
  [182. 488.]]]
[INFO] ArUco marke

[[[455. 374.]
  [588. 379.]
  [588. 515.]
  [454. 507.]]]
[INFO] ArUco marker ID: 8
[[[322. 368.]
  [441. 373.]
  [441. 504.]
  [322. 493.]]]
[INFO] ArUco marker ID: 7
[[[204. 362.]
  [310. 367.]
  [309. 492.]
  [198. 483.]]]
[INFO] ArUco marker ID: 6
[[[212. 231.]
  [316. 229.]
  [310. 353.]
  [205. 349.]]]
[INFO] ArUco marker ID: 3
[[[327. 229.]
  [443. 226.]
  [441. 358.]
  [322. 354.]]]
[INFO] ArUco marker ID: 4
[[[456. 227.]
  [588. 224.]
  [589. 363.]
  [455. 359.]]]
[INFO] ArUco marker ID: 5
[[[229. 109.]
  [328.  99.]
  [316. 216.]
  [213. 218.]]]
[INFO] ArUco marker ID: 0
[[[339.  99.]
  [450.  86.]
  [444. 213.]
  [329. 216.]]]
[INFO] ArUco marker ID: 1
[[[463.  85.]
  [590.  73.]
  [589. 210.]
  [457. 212.]]]
[INFO] ArUco marker ID: 2
[[[455. 374.]
  [589. 379.]
  [589. 515.]
  [455. 506.]]]
[INFO] ArUco marker ID: 8
[[[322. 368.]
  [441. 373.]
  [441. 505.]
  [322. 493.]]]
[INFO] ArUco marker ID: 7
[[[204. 363.]
  [310. 368.]
  [310. 493.]
  [198. 484.]]]
[INFO] ArUco marke

[[[326. 366.]
  [445. 371.]
  [445. 502.]
  [326. 491.]]]
[INFO] ArUco marker ID: 7
[[[459. 371.]
  [593. 375.]
  [593. 510.]
  [460. 503.]]]
[INFO] ArUco marker ID: 8
[[[208. 362.]
  [314. 367.]
  [314. 491.]
  [202. 484.]]]
[INFO] ArUco marker ID: 6
[[[214. 231.]
  [318. 228.]
  [314. 352.]
  [208. 349.]]]
[INFO] ArUco marker ID: 3
[[[330. 228.]
  [446. 225.]
  [445. 356.]
  [327. 353.]]]
[INFO] ArUco marker ID: 4
[[[459. 225.]
  [592. 221.]
  [593. 359.]
  [459. 357.]]]
[INFO] ArUco marker ID: 5
[[[230. 110.]
  [329.  98.]
  [319. 215.]
  [216. 219.]]]
[INFO] ArUco marker ID: 0
[[[340.  97.]
  [450.  84.]
  [447. 210.]
  [331. 215.]]]
[INFO] ArUco marker ID: 1
[[[325. 366.]
  [445. 370.]
  [445. 501.]
  [325. 491.]]]
[INFO] ArUco marker ID: 7
[[[459. 370.]
  [592. 374.]
  [593. 509.]
  [459. 502.]]]
[INFO] ArUco marker ID: 8
[[[206. 362.]
  [313. 366.]
  [313. 491.]
  [200. 485.]]]
[INFO] ArUco marker ID: 6
[[[213. 231.]
  [318. 228.]
  [313. 351.]
  [207. 349.]]]
[INFO] ArUco marke

[[[316. 368.]
  [437. 372.]
  [439. 503.]
  [318. 494.]]]
[INFO] ArUco marker ID: 7
[[[451. 372.]
  [587. 375.]
  [588. 510.]
  [453. 504.]]]
[INFO] ArUco marker ID: 8
[[[201. 363.]
  [304. 368.]
  [305. 494.]
  [195. 485.]]]
[INFO] ArUco marker ID: 6
[[[207. 231.]
  [306. 227.]
  [304. 354.]
  [202. 350.]]]
[INFO] ArUco marker ID: 3
[[[317. 227.]
  [434. 223.]
  [437. 357.]
  [317. 355.]]]
[INFO] ArUco marker ID: 4
[[[449. 223.]
  [584. 220.]
  [587. 359.]
  [451. 358.]]]
[INFO] ArUco marker ID: 5
[[[218. 105.]
  [309.  91.]
  [306. 214.]
  [208. 218.]]]
[INFO] ArUco marker ID: 0
[[[322.  89.]
  [435.  76.]
  [435. 209.]
  [318. 213.]]]
[INFO] ArUco marker ID: 1
[[[448.  75.]
  [584.  65.]
  [585. 205.]
  [449. 209.]]]
[INFO] ArUco marker ID: 2
[[[452. 373.]
  [586. 374.]
  [589. 508.]
  [455. 505.]]]
[INFO] ArUco marker ID: 8
[[[316. 369.]
  [437. 372.]
  [440. 503.]
  [320. 494.]]]
[INFO] ArUco marker ID: 7
[[[202. 364.]
  [304. 369.]
  [306. 494.]
  [198. 485.]]]
[INFO] ArUco marke

[[[451. 378.]
  [588. 379.]
  [590. 515.]
  [455. 511.]]]
[INFO] ArUco marker ID: 8
[[[314. 374.]
  [437. 378.]
  [440. 510.]
  [317. 501.]]]
[INFO] ArUco marker ID: 7
[[[202. 368.]
  [302. 374.]
  [305. 500.]
  [198. 490.]]]
[INFO] ArUco marker ID: 6
[[[313. 230.]
  [432. 227.]
  [436. 364.]
  [313. 360.]]]
[INFO] ArUco marker ID: 4
[[[206. 234.]
  [301. 231.]
  [301. 360.]
  [203. 355.]]]
[INFO] ArUco marker ID: 3
[[[446. 227.]
  [586. 224.]
  [588. 364.]
  [451. 364.]]]
[INFO] ArUco marker ID: 5
[[[214. 105.]
  [302.  90.]
  [302. 216.]
  [208. 222.]]]
[INFO] ArUco marker ID: 0
[[[314.  88.]
  [429.  75.]
  [432. 213.]
  [313. 217.]]]
[INFO] ArUco marker ID: 1
[[[443.  73.]
  [583.  63.]
  [586. 208.]
  [446. 212.]]]
[INFO] ArUco marker ID: 2
[[[451. 379.]
  [588. 379.]
  [591. 514.]
  [455. 511.]]]
[INFO] ArUco marker ID: 8
[[[314. 374.]
  [437. 378.]
  [440. 510.]
  [318. 501.]]]
[INFO] ArUco marker ID: 7
[[[202. 368.]
  [302. 374.]
  [305. 501.]
  [199. 490.]]]
[INFO] ArUco marke

[[[455. 379.]
  [592. 380.]
  [595. 514.]
  [460. 511.]]]
[INFO] ArUco marker ID: 8
[[[319. 375.]
  [441. 379.]
  [445. 510.]
  [323. 501.]]]
[INFO] ArUco marker ID: 7
[[[208. 369.]
  [307. 376.]
  [311. 501.]
  [205. 489.]]]
[INFO] ArUco marker ID: 6
[[[317. 232.]
  [435. 229.]
  [441. 365.]
  [318. 361.]]]
[INFO] ArUco marker ID: 4
[[[211. 236.]
  [305. 233.]
  [307. 360.]
  [209. 356.]]]
[INFO] ArUco marker ID: 3
[[[449. 228.]
  [589. 225.]
  [592. 365.]
  [454. 365.]]]
[INFO] ArUco marker ID: 5
[[[218. 106.]
  [306.  91.]
  [306. 218.]
  [212. 223.]]]
[INFO] ArUco marker ID: 0
[[[317.  90.]
  [431.  76.]
  [435. 214.]
  [318. 219.]]]
[INFO] ArUco marker ID: 1
[[[445.  75.]
  [586.  65.]
  [589. 210.]
  [449. 214.]]]
[INFO] ArUco marker ID: 2
[[[455. 379.]
  [592. 380.]
  [595. 514.]
  [460. 511.]]]
[INFO] ArUco marker ID: 8
[[[319. 375.]
  [441. 379.]
  [445. 510.]
  [323. 501.]]]
[INFO] ArUco marker ID: 7
[[[208. 369.]
  [307. 376.]
  [311. 501.]
  [205. 489.]]]
[INFO] ArUco marke

[[[456. 380.]
  [592. 383.]
  [594. 519.]
  [458. 513.]]]
[INFO] ArUco marker ID: 8
[[[320. 375.]
  [441. 380.]
  [443. 512.]
  [323. 500.]]]
[INFO] ArUco marker ID: 7
[[[209. 368.]
  [308. 374.]
  [311. 500.]
  [205. 489.]]]
[INFO] ArUco marker ID: 6
[[[320. 232.]
  [438. 230.]
  [441. 365.]
  [320. 361.]]]
[INFO] ArUco marker ID: 4
[[[214. 235.]
  [308. 232.]
  [308. 360.]
  [209. 354.]]]
[INFO] ArUco marker ID: 3
[[[452. 229.]
  [591. 227.]
  [592. 368.]
  [456. 366.]]]
[INFO] ArUco marker ID: 5
[[[221. 106.]
  [310.  92.]
  [309. 219.]
  [214. 222.]]]
[INFO] ArUco marker ID: 0
[[[321.  90.]
  [436.  78.]
  [438. 215.]
  [320. 218.]]]
[INFO] ArUco marker ID: 1
[[[449.  77.]
  [589.  67.]
  [591. 212.]
  [452. 215.]]]
[INFO] ArUco marker ID: 2
[[[456. 380.]
  [592. 383.]
  [594. 519.]
  [458. 512.]]]
[INFO] ArUco marker ID: 8
[[[320. 374.]
  [442. 381.]
  [444. 511.]
  [323. 500.]]]
[INFO] ArUco marker ID: 7
[[[208. 368.]
  [308. 374.]
  [311. 500.]
  [204. 488.]]]
[INFO] ArUco marke

[[[458. 390.]
  [594. 398.]
  [591. 539.]
  [454. 525.]]]
[INFO] ArUco marker ID: 8
[[[323. 381.]
  [444. 390.]
  [439. 525.]
  [321. 509.]]]
[INFO] ArUco marker ID: 7
[[[205. 374.]
  [311. 381.]
  [308. 508.]
  [197. 497.]]]
[INFO] ArUco marker ID: 6
[[[214. 240.]
  [317. 240.]
  [311. 366.]
  [206. 360.]]]
[INFO] ArUco marker ID: 3
[[[329. 239.]
  [446. 239.]
  [443. 375.]
  [323. 367.]]]
[INFO] ArUco marker ID: 4
[[[461. 239.]
  [597. 241.]
  [594. 383.]
  [458. 376.]]]
[INFO] ArUco marker ID: 5
[[[230. 113.]
  [325. 103.]
  [318. 226.]
  [216. 227.]]]
[INFO] ArUco marker ID: 0
[[[337. 102.]
  [450.  91.]
  [447. 225.]
  [329. 226.]]]
[INFO] ArUco marker ID: 1
[[[457. 392.]
  [594. 400.]
  [591. 541.]
  [453. 529.]]]
[INFO] ArUco marker ID: 8
[[[322. 383.]
  [442. 392.]
  [439. 527.]
  [319. 512.]]]
[INFO] ArUco marker ID: 7
[[[204. 375.]
  [310. 383.]
  [305. 511.]
  [195. 499.]]]
[INFO] ArUco marker ID: 6
[[[461. 240.]
  [596. 242.]
  [594. 385.]
  [457. 378.]]]
[INFO] ArUco marke